/** Rule-based ISO 13485 / MDR procedure bodies for audit-critical SOPs. */

type Locale = "tr" | "en";

function revTable(locale: Locale): string {
  if (locale === "tr") {
    return [
      "## 8. Revizyon geçmişi",
      "",
      "| Rev | Tarih | Açıklama |",
      "|-----|-------|----------|",
      "| 00 | [TBC] | İlk yayın |",
    ].join("\n");
  }
  return [
    "## 8. Revision history",
    "",
    "| Rev | Date | Description |",
    "|-----|------|-------------|",
    "| 00 | [TBC] | Initial issue |",
  ].join("\n");
}

export function buildSopCapaProcedure(locale: Locale): string {
  if (locale === "tr") {
    return [
      "## 1. Amaç",
      "",
      "Düzeltici ve önleyici faaliyetlerin (CAPA) EN ISO 13485:2016 Madde 8.5.2–8.5.3 ve MDR PMS/CAPA arayüzü kapsamında sistematik yönetimini tanımlar.",
      "",
      "## 2. Kapsam",
      "",
      "Şikâyetler, iç tetkik bulguları, uygunsuz ürün, vigilans, tedarikçi, proses ve kalite kayıtlarından kaynaklanan CAPA'lar.",
      "",
      "## 3. Sorumluluklar",
      "",
      "- **CAPA sahibi:** Kayıt açar, kök neden analizi ve aksiyon planı yürütür.",
      "- **Kalite Müdürü:** CAPA onayı, etkinlik doğrulaması ve kapanış.",
      "- **Süreç sahibi:** Düzeltici/önleyici aksiyonları uygular.",
      "- **PRRC:** Vigilans ve MDR bildirim gerekliliğini değerlendirir.",
      "",
      "## 4. Prosedür",
      "",
      "### 4.1 CAPA açılışı",
      "4.1.1 Kaynak belirlenir (şikâyet, iç tetkik, NCP, trend, yönetim gözden geçirme).",
      "4.1.2 FORM-CAPA-01 doldurulur; referans no ve hedef tarih atanır.",
      "",
      "### 4.2 Kök neden analizi",
      "4.2.1 5 Neden, balık kılçığı veya eşdeğer yöntem uygulanır.",
      "4.2.2 Risk dosyası (ISO 14971) ve etkilenen dokümanlar güncellenir.",
      "",
      "### 4.3 Düzeltici ve önleyici aksiyon",
      "4.3.1 Düzeltme (containment) ve düzeltici aksiyon planlanır.",
      "4.3.2 Önleyici aksiyon gerekiyorsa ayrı veya aynı kayıtta izlenir.",
      "",
      "### 4.4 Etkinlik doğrulaması ve kapanış",
      "4.4.1 Aksiyonlar tamamlandıktan sonra etkinlik doğrulanır.",
      "4.4.2 Kapanış onayı Kalite Müdürü tarafından verilir; kayıt arşivlenir.",
      "",
      "## 5. Kayıtlar",
      "",
      "FORM-CAPA-01, CAPA kayıt defteri, kök neden analizi, etkinlik doğrulama kanıtı, eğitim kayıtları.",
      "",
      "## 6. Referanslar",
      "",
      "EN ISO 13485:2016 (8.5.2, 8.5.3); MDR 2017/745; SOP-CH; SOP-IA; SOP-VG; SOP-NCP.",
      "",
      revTable(locale),
    ].join("\n");
  }
  return [
    "## 1. Purpose",
    "",
    "Defines systematic management of corrective and preventive action (CAPA) per EN ISO 13485:2016 Clauses 8.5.2–8.5.3 and MDR PMS/CAPA interfaces.",
    "",
    "## 2. Scope",
    "",
    "CAPAs from complaints, internal audit findings, nonconforming product, vigilance, suppliers, process and quality records.",
    "",
    "## 3. Responsibilities",
    "",
    "- **CAPA owner:** Opens record, performs root cause analysis and action plan.",
    "- **Quality Manager:** CAPA approval, effectiveness verification and closure.",
    "- **Process owner:** Implements corrective/preventive actions.",
    "- **PRRC:** Assesses vigilance and MDR reporting requirements.",
    "",
    "## 4. Procedure",
    "",
    "### 4.1 CAPA initiation",
    "4.1.1 Identify source (complaint, internal audit, NCP, trend, management review).",
    "4.1.2 Complete FORM-CAPA-01; assign reference no and target date.",
    "",
    "### 4.2 Root cause analysis",
    "4.2.1 Apply 5-Why, fishbone or equivalent method.",
    "4.2.2 Update risk file (ISO 14971) and affected documents.",
    "",
    "### 4.3 Corrective and preventive action",
    "4.3.1 Plan containment and corrective action.",
    "4.3.2 Track preventive action in same or separate record when required.",
    "",
    "### 4.4 Effectiveness verification and closure",
    "4.4.1 Verify effectiveness after actions are completed.",
    "4.4.2 Quality Manager grants closure approval; record archived.",
    "",
    "## 5. Records",
    "",
    "FORM-CAPA-01, CAPA register, root cause analysis, effectiveness evidence, training records.",
    "",
    "## 6. References",
    "",
    "EN ISO 13485:2016 (8.5.2, 8.5.3); MDR 2017/745; SOP-CH; SOP-IA; SOP-VG; SOP-NCP.",
    "",
    revTable(locale),
  ].join("\n");
}

export function buildSopIaProcedure(locale: Locale): string {
  if (locale === "tr") {
    return [
      "## 1. Amaç",
      "İç kalite tetkik programının planlanması, yürütülmesi, raporlanması ve bulguların CAPA'ya bağlanmasını tanımlar (ISO 13485 Madde 8.2.4).",
      "",
      "## 2. Kapsam",
      "KYS kapsamındaki tüm süreçler; yıllık tetkik planı (PLAN-IA-01) ve tetkik kayıtları (FORM-IA-01, REC-IA-01).",
      "",
      "## 3. Sorumluluklar",
      "- **Kalite Müdürü:** Tetkik programını onaylar.",
      "- **Baş denetçi:** Tetkik planlar, yürütür ve raporlar.",
      "- **Denetlenen süreç sahibi:** Bulgulara yanıt verir; CAPA açar.",
      "",
      "## 4. Prosedür",
      "4.1 Yıllık iç tetkik planı hazırlanır (kapsam, kriter, frekans, denetçi bağımsızlığı).",
      "4.2 Tetkik öncesi hazırlık ve açılış toplantısı yapılır.",
      "4.3 Kanıt toplanır; uygunsuzluklar ve gözlemler sınıflandırılır (majör/minör).",
      "4.4 Kapanış toplantısı ve FORM-IA-01 raporu tamamlanır.",
      "4.5 Majör/minör bulgular için CAPA açılır; etkinlik doğrulaması izlenir.",
      "",
      "## 5. Kayıtlar",
      "PLAN-IA-01, FORM-IA-01, REC-IA-01, CAPA referansları, yönetim gözden geçirme girdileri.",
      "",
      "## 6. Referanslar",
      "EN ISO 13485:2016 (8.2.4); SOP-CAPA; SOP-MR.",
      "",
      revTable(locale),
    ].join("\n");
  }
  return [
    "## 1. Purpose",
    "Defines planning, execution, reporting of internal quality audits and linkage of findings to CAPA (ISO 13485 Clause 8.2.4).",
    "",
    "## 2. Scope",
    "All processes within QMS scope; annual audit plan (PLAN-IA-01) and audit records (FORM-IA-01, REC-IA-01).",
    "",
    "## 3. Responsibilities",
    "- **Quality Manager:** Approves audit programme.",
    "- **Lead auditor:** Plans, conducts and reports audits.",
    "- **Auditee process owner:** Responds to findings; opens CAPA.",
    "",
    "## 4. Procedure",
    "4.1 Prepare annual internal audit plan (scope, criteria, frequency, auditor independence).",
    "4.2 Pre-audit preparation and opening meeting.",
    "4.3 Collect evidence; classify nonconformities and observations (major/minor).",
    "4.4 Closing meeting and complete FORM-IA-01 report.",
    "4.5 Open CAPA for major/minor findings; track effectiveness verification.",
    "",
    "## 5. Records",
    "PLAN-IA-01, FORM-IA-01, REC-IA-01, CAPA references, management review inputs.",
    "",
    "## 6. References",
    "EN ISO 13485:2016 (8.2.4); SOP-CAPA; SOP-MR.",
    "",
    revTable(locale),
  ].join("\n");
}

export function buildSopVgProcedure(locale: Locale): string {
  if (locale === "tr") {
    return [
      "## 1. Amaç",
      "Piyasa sonrası ciddi olayların ve ilgili güvenlik düzeltici faaliyetlerinin MDR Madde 87–90 ve IMDRF kapsamında bildirilmesini tanımlar.",
      "",
      "## 2. Kapsam",
      "AB pazarında dağıtılan tıbbi cihazlar; şikâyet, kullanıcı geri bildirimi ve PMS kaynaklı olaylar.",
      "",
      "## 3. Sorumluluklar",
      "- **PRRC:** Vigilans sınıflandırması, süre hesabı ve yetkili otorite/NB bildirimi.",
      "- **Kalite Müdürü:** CAPA ve FSCA koordinasyonu.",
      "- **Tüm personel:** Olayı derhal bildirir.",
      "",
      "## 4. Prosedür",
      "4.1 Olay farkındalık tarihi kaydedilir.",
      "4.2 Ciddiyet sınıflandırması: ölüm/ciddi kötüleşme (10 gün), ciddi olay (15 gün), diğer (30 gün) — MDR Art. 87.",
      "4.3 FORM-VG-01 ile ilk bildirim hazırlanır; EUDAMED/NB kanalı kullanılır.",
      "4.4 Takip raporları ve FSCA (SOP-AN) ile koordinasyon sağlanır.",
      "4.5 PSUR ve CER güncellemelerine veri aktarılır.",
      "",
      "## 5. Kayıtlar",
      "FORM-VG-01, WI-VG-01, bildirim kanıtı, CAPA/FSCA referansları, süre takip kaydı.",
      "",
      "## 6. Referanslar",
      "MDR 2017/745 (Art. 87–90); IMDRF; SOP-CH; SOP-AN; SOP-CAPA.",
      "",
      revTable(locale),
    ].join("\n");
  }
  return [
    "## 1. Purpose",
    "Defines reporting of post-market serious incidents and related safety corrective actions per MDR Articles 87–90 and IMDRF.",
    "",
    "## 2. Scope",
    "Medical devices placed on the EU market; events from complaints, user feedback and PMS.",
    "",
    "## 3. Responsibilities",
    "- **PRRC:** Vigilance classification, deadline calculation and competent authority/NB notification.",
    "- **Quality Manager:** CAPA and FSCA coordination.",
    "- **All personnel:** Report events immediately.",
    "",
    "## 4. Procedure",
    "4.1 Record date of awareness of the event.",
    "4.2 Severity classification: death/serious deterioration (10 days), serious incident (15 days), other (30 days) — MDR Art. 87.",
    "4.3 Prepare initial report with FORM-VG-01; use EUDAMED/NB channel.",
    "4.4 Coordinate follow-up reports and FSCA (SOP-AN).",
    "4.5 Feed data into PSUR and CER updates.",
    "",
    "## 5. Records",
    "FORM-VG-01, WI-VG-01, notification evidence, CAPA/FSCA references, deadline tracking.",
    "",
    "## 6. References",
    "MDR 2017/745 (Art. 87–90); IMDRF; SOP-CH; SOP-AN; SOP-CAPA.",
    "",
    revTable(locale),
  ].join("\n");
}

export function buildSopDcProcedure(locale: Locale): string {
  if (locale === "tr") {
    return [
      "## 1. Amaç",
      "KYS dokümanlarının oluşturulması, gözden geçirilmesi, onaylanması, dağıtımı ve geçersiz kılınmasını tanımlar (ISO 13485 Madde 4.2.4).",
      "",
      "## 2. Kapsam",
      "El kitabı, prosedürler, talimatlar, formlar, listeler ve dış kaynaklı dokümanlar.",
      "",
      "## 3. Prosedür",
      "3.1 Dokümanlar benzersiz kod ve revizyon numarası ile tanımlanır.",
      "3.2 Taslak → İncelemede → Onaylı durum geçişleri kontrollüdür; çok adımlı onay (inceleyen → onaylayan → yayın) uygulanır.",
      "3.3 Onaylı kopyalar MDRpilot üzerinden erişilir; yazdırılmış kopyalar kontrollü dağıtım listesinde (LIST-DC-01).",
      "3.4 Periyodik gözden geçirme (en geç 1 yıl) ve revizyon geçmişi tutulur.",
      "3.5 Geçersiz dokümanlar arşivlenir; eski revizyonlar yanlışlıkla kullanılmaz.",
      "",
      "## 4. Kayıtlar",
      "LIST-DC-01, onay kayıtları, revizyon geçmişi, eğitim kayıtları (SOP revizyonu sonrası).",
      "",
      "## 5. Referanslar",
      "EN ISO 13485:2016 (4.2.4); SOP-CC; SOP-HR.",
      "",
      revTable(locale),
    ].join("\n");
  }
  return [
    "## 1. Purpose",
    "Defines creation, review, approval, distribution and obsolescence of QMS documents (ISO 13485 Clause 4.2.4).",
    "",
    "## 2. Scope",
    "Manual, procedures, work instructions, forms, lists and external documents.",
    "",
    "## 3. Procedure",
    "3.1 Documents identified by unique code and revision number.",
    "3.2 Controlled transitions Draft → In Review → Approved; multi-step approval (reviewer → approver → release).",
    "3.3 Approved copies accessed via MDRpilot; printed copies on controlled distribution list (LIST-DC-01).",
    "3.4 Periodic review (at least annually) and revision history maintained.",
    "3.5 Obsolete documents archived; superseded revisions prevented from use.",
    "",
    "## 4. Records",
    "LIST-DC-01, approval records, revision history, training records (after SOP revision).",
    "",
    "## 5. References",
    "EN ISO 13485:2016 (4.2.4); SOP-CC; SOP-HR.",
    "",
    revTable(locale),
  ].join("\n");
}

export function buildSopDdProcedure(locale: Locale): string {
  if (locale === "tr") {
    return [
      "## 1. Amaç",
      "Tıbbi cihaz tasarım ve geliştirme sürecini ISO 13485 Madde 7.3 ve MDR teknik dosya gereklilikleri kapsamında tanımlar.",
      "",
      "## 2. Kapsam",
      "Yeni tasarım, tasarım değişikliği ve yazılım içeren cihazlar; DHF, risk dosyası ve V&V kayıtları.",
      "",
      "## 3. Tasarım aşamaları",
      "7.3.2 Tasarım girdileri — kullanıcı ihtiyaçları, regülasyon, risk.",
      "7.3.3 Tasarım çıktıları — spesifikasyon, çizim, yazılım, etiket.",
      "7.3.4 Tasarım gözden geçirme — aşamalı onay.",
      "7.3.5 Tasarım doğrulama — spesifikasyon karşılanması.",
      "7.3.6 Tasarım validasyonu — amaçlanan kullanım.",
      "7.3.7 Tasarım transferi — üretim.",
      "7.3.8 Tasarım değişiklikleri — SOP-CC ile entegre.",
      "",
      "## 4. İzlenebilirlik",
      "Tasarım girdisi → risk → çıktı → V&V → klinik değerlendirme bağlantıları ürün DHF panelinde izlenir.",
      "",
      "## 5. Kayıtlar",
      "SPEC-PRD-01, DHF, risk dosyası, V&V raporları, tasarım gözden geçirme kayıtları.",
      "",
      "## 6. Referanslar",
      "EN ISO 13485:2016 (7.3); MDR Annex II; ISO 14971; IEC 62304; SOP-RM; SOP-CC.",
      "",
      revTable(locale),
    ].join("\n");
  }
  return [
    "## 1. Purpose",
    "Defines medical device design and development per ISO 13485 Clause 7.3 and MDR technical documentation requirements.",
    "",
    "## 2. Scope",
    "New design, design changes and software-containing devices; DHF, risk file and V&V records.",
    "",
    "## 3. Design stages",
    "7.3.2 Design inputs — user needs, regulation, risk.",
    "7.3.3 Design outputs — specification, drawings, software, labeling.",
    "7.3.4 Design review — stage-gate approval.",
    "7.3.5 Design verification — specification met.",
    "7.3.6 Design validation — intended use.",
    "7.3.7 Design transfer — manufacturing.",
    "7.3.8 Design changes — integrated with SOP-CC.",
    "",
    "## 4. Traceability",
    "Design input → risk → output → V&V → clinical evaluation links tracked in product DHF panel.",
    "",
    "## 5. Records",
    "SPEC-PRD-01, DHF, risk file, V&V reports, design review records.",
    "",
    "## 6. References",
    "EN ISO 13485:2016 (7.3); MDR Annex II; ISO 14971; IEC 62304; SOP-RM; SOP-CC.",
    "",
    revTable(locale),
  ].join("\n");
}
