/** Deterministic form templates for KYS child documents (not procedure text). */

import { buildGenericFormContent } from "./layer-content-templates";

function formHeader(
  locale: "tr" | "en",
  code: string,
  title: string,
  parentProcedureCode?: string | null,
): string {
  const parent = parentProcedureCode?.trim() || "—";
  if (locale === "tr") {
    return [
      `# ${code} — ${title}`,
      "",
      "> Form şablonu — prosedür metni değildir. Alanları doldurun veya yazdırıp kullanın.",
      "",
      "## Form bilgileri",
      "",
      "| Alan | Değer |",
      "|------|-------|",
      "| Form kodu | " + code + " |",
      "| Revizyon | 00 |",
      "| İlgili prosedür | " + parent + " |",
      "| Tarih | __________ |",
      "| Referans no | __________ |",
    ].join("\n");
  }
  return [
    `# ${code} — ${title}`,
    "",
    "> Form template — not a procedure. Fill fields or print for use.",
    "",
    "## Form information",
    "",
    "| Field | Value |",
    "|-------|-------|",
    "| Form code | " + code + " |",
    "| Revision | 00 |",
    "| Related procedure | " + parent + " |",
    "| Date | __________ |",
    "| Reference no | __________ |",
  ].join("\n");
}

function approvalBlock(locale: "tr" | "en"): string {
  if (locale === "tr") {
    return [
      "## Onay",
      "",
      "| Rol | Ad / imza | Tarih |",
      "|-----|-----------|-------|",
      "| Hazırlayan | | |",
      "| Kalite Müdürü | | |",
      "| Onay (üst yönetim / PRRC) | | |",
    ].join("\n");
  }
  return [
    "## Approval",
    "",
    "| Role | Name / signature | Date |",
    "|------|------------------|------|",
    "| Prepared by | | |",
    "| Quality Manager | | |",
    "| Approved by (top management / PRRC) | | |",
  ].join("\n");
}

export function buildFormAn01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-AN-01",
    locale === "tr" ? "FSCA Başlatma ve İlk Değerlendirme Formu" : "FSCA Initiation and Initial Assessment Form",
    "SOP-AN",
  );
  const body =
    locale === "tr"
      ? [
          "## Ürün ve olay bilgisi",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Ürün adı | __________ |",
          "| Model / referans | __________ |",
          "| UDI-DI / UDI-PI | __________ |",
          "| Lot / seri no | __________ |",
          "| Cihaz sınıfı | __________ |",
          "| Şikâyet ref (FORM-CH-01) | __________ |",
          "| Vigilans ref (SOP-VG) | __________ |",
          "",
          "## İlk değerlendirme",
          "",
          "| Soru | EVET | HAYIR | Not |",
          "|------|------|-------|-----|",
          "| Hasta / kullanıcı emniyet riski var mı? | ☐ | ☐ | |",
          "| Dağıtımda ürün var mı? | ☐ | ☐ | |",
          "| FSCA (geri çağırma / düzeltici saha aksiyonu) gerekli mi? | ☐ | ☐ | |",
          "| Danışma bildirimi yeterli mi? | ☐ | ☐ | |",
          "",
          "**Risk özeti:** _______________________________________________",
          "",
          "**Geçici kontrol (karantina / sevkiyat durdurma):** _____________",
          "",
          "## Karar",
          "",
          "| Karar | Seçim |",
          "|-------|-------|",
          "| Danışma bildirimi (FORM-AN-03) | ☐ |",
          "| FSCA başlat (FORM-AN-02, FORM-AN-04…) | ☐ |",
          "| İzleme / risk azaltma (SOP-RM) | ☐ |",
          "| Kapat — ek aksiyon yok | ☐ |",
          "",
          "**Sorumlu:** __________  **Hedef tarih:** __________",
          "",
          "## Örnek (doldurulmuş)",
          "",
          "| Alan | Örnek |",
          "|------|-------|",
          "| Olay no | AN-2026-004 |",
          "| Ürün | Örnek steril set — Model ST-100 |",
          "| Şikâyet ref | FORM-CH-01 / CH-2026-012 |",
          "| Karar | FSCA başlat — FSN hazırlanacak |",
        ].join("\n")
      : [
          "## Product and event information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Product name | __________ |",
          "| Model / reference | __________ |",
          "| UDI-DI / UDI-PI | __________ |",
          "| Lot / serial no | __________ |",
          "| Device class | __________ |",
          "| Complaint ref (FORM-CH-01) | __________ |",
          "| Vigilance ref (SOP-VG) | __________ |",
          "",
          "## Initial assessment",
          "",
          "| Question | YES | NO | Note |",
          "|----------|-----|----|-----|",
          "| Patient / user safety risk? | ☐ | ☐ | |",
          "| Product in distribution? | ☐ | ☐ | |",
          "| FSCA required? | ☐ | ☐ | |",
          "| Advisory notice sufficient? | ☐ | ☐ | |",
          "",
          "**Risk summary:** _______________________________________________",
          "",
          "**Interim control (quarantine / stop shipment):** _____________",
          "",
          "## Decision",
          "",
          "| Decision | Select |",
          "|----------|--------|",
          "| Advisory notice (FORM-AN-03) | ☐ |",
          "| Initiate FSCA (FORM-AN-02, FORM-AN-04…) | ☐ |",
          "| Monitor / risk reduction (SOP-RM) | ☐ |",
          "| Close — no further action | ☐ |",
          "",
          "**Owner:** __________  **Target date:** __________",
          "",
          "## Example (filled)",
          "",
          "| Field | Example |",
          "|-------|---------|",
          "| Event no | AN-2026-004 |",
          "| Product | Sample sterile kit — Model ST-100 |",
          "| Complaint ref | FORM-CH-01 / CH-2026-012 |",
          "| Decision | Initiate FSCA — prepare FSN |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormAn02(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-AN-02",
    locale === "tr" ? "Saha Güvenlik Bildirimi (FSN) Şablonu" : "Field Safety Notice (FSN) Template",
    "SOP-AN",
  );
  const body =
    locale === "tr"
      ? [
          "## FSN metni",
          "",
          "**Ürün tanımı:** __________________________________________",
          "",
          "**UDI / lot / seri:** _____________________________________",
          "",
          "**Sorun açıklaması:** ______________________________________",
          "",
          "**Risk açıklaması:** ______________________________________",
          "",
          "**Kullanıcı / sağlık kuruluşu eylemi:** _____________________",
          "",
          "**Takvim (son tarih):** ____________________________________",
          "",
          "**İletişim (7/24):** ______________________________________",
          "",
          "**İade / geri çağırma talimatı:** __________________________",
          "",
          "## Dağıtım onayı",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| FSN ref | FSN-________ |",
          "| Onaylayan | __________ |",
          "| Dağıtım başlangıç | __________ |",
        ].join("\n")
      : [
          "## FSN text",
          "",
          "**Device description:** ____________________________________",
          "",
          "**UDI / lot / serial:** ____________________________________",
          "",
          "**Problem description:** ___________________________________",
          "",
          "**Risk description:** ______________________________________",
          "",
          "**User / healthcare action:** ______________________________",
          "",
          "**Timeline (deadline):** ___________________________________",
          "",
          "**Contact (24/7):** ________________________________________",
          "",
          "**Return / recall instruction:** _____________________________",
          "",
          "## Distribution approval",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| FSN ref | FSN-________ |",
          "| Approved by | __________ |",
          "| Distribution start | __________ |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormAn03(locale: "tr" | "en"): string {
  const h = formHeader(locale, "FORM-AN-03", locale === "tr" ? "Danışma Duyurusu Şablonu" : "Advisory Notice Template", "SOP-AN");
  const body =
    locale === "tr"
      ? [
          "## Danışma metni (emniyet riski olmayan duyurular)",
          "",
          "**Konu:** __________________________________________________",
          "",
          "**Ürün / model:** __________________________________________",
          "",
          "**Açıklama / netleştirme:** ________________________________",
          "",
          "**Önerilen eylem:** ________________________________________",
          "",
          "**İletişim:** ______________________________________________",
        ].join("\n")
      : [
          "## Advisory notice text (non-safety)",
          "",
          "**Subject:** _______________________________________________",
          "",
          "**Product / model:** _______________________________________",
          "",
          "**Clarification:** _________________________________________",
          "",
          "**Recommended action:** ____________________________________",
          "",
          "**Contact:** _______________________________________________",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormAn04(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-AN-04",
    locale === "tr" ? "FSN Dağıtım ve Okundu Teyit Formu" : "FSN Distribution and Read-Receipt Log",
    "SOP-AN",
  );
  const body =
    locale === "tr"
      ? [
          "## Dağıtım kaydı",
          "",
          "| Alıcı | Ülke | Kanal | Gönderim tarihi | Teslim teyidi | Okundu onayı | Sorumlu |",
          "|-------|------|-------|-----------------|---------------|--------------|---------|",
          "| | | | | ☐ | ☐ | |",
          "| | | | | ☐ | ☐ | |",
          "| | | | | ☐ | ☐ | |",
          "",
          "**FSN ref:** __________  **Toplam alıcı:** __________",
        ].join("\n")
      : [
          "## Distribution log",
          "",
          "| Recipient | Country | Channel | Dispatch date | Delivery OK | Read receipt | Owner |",
          "|-----------|---------|---------|---------------|-------------|--------------|-------|",
          "| | | | | ☐ | ☐ | |",
          "| | | | | ☐ | ☐ | |",
          "| | | | | ☐ | ☐ | |",
          "",
          "**FSN ref:** __________  **Total recipients:** __________",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormAn05(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-AN-05",
    locale === "tr" ? "RMA / İade / Geri Çağırma Takip Formu" : "RMA / Return / Recall Tracking Form",
    "SOP-AN",
  );
  const body =
    locale === "tr"
      ? [
          "## İade / geri çağırma takibi",
          "",
          "| RMA no | Ürün / lot | Adet | İade durumu | Karantina | İmha / onarım | İzlenebilirlik (SOP-TR) |",
          "|--------|------------|------|-------------|-----------|--------------|-------------------------|",
          "| | | | | ☐ | ☐ | |",
          "| | | | | ☐ | ☐ | |",
          "",
          "**Hedef iade oranı %:** __________  **Gerçekleşen %:** __________",
        ].join("\n")
      : [
          "## Return / recall tracking",
          "",
          "| RMA no | Product / lot | Qty | Return status | Quarantine | Dispose / repair | Traceability (SOP-TR) |",
          "|--------|---------------|-----|---------------|------------|------------------|----------------------|",
          "| | | | | ☐ | ☐ | |",
          "| | | | | ☐ | ☐ | |",
          "",
          "**Target return %:** __________  **Actual %:** __________",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormAn06(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-AN-06",
    locale === "tr" ? "FSCA Etkililik Doğrulama Kontrol Listesi" : "FSCA Effectiveness Verification Checklist",
    "SOP-AN",
  );
  const body =
    locale === "tr"
      ? [
          "## Etkililik kontrol listesi",
          "",
          "| Kontrol | Hedef | Sonuç | EVET | HAYIR | Not |",
          "|---------|-------|-------|------|-------|-----|",
          "| Dağıtım kapsamı (%) | ≥90 | | ☐ | ☐ | |",
          "| İade / aksiyon tamamlama (%) | ≥95 | | ☐ | ☐ | |",
          "| Numune kontrol yapıldı | — | | ☐ | ☐ | |",
          "| Müşteri teyitleri alındı | — | | ☐ | ☐ | |",
          "| CAPA gerekli (FORM-CAPA-01) | — | | ☐ | ☐ | |",
          "",
          "**FSCA kapanış onayı:** __________  **Tarih:** __________",
        ].join("\n")
      : [
          "## Effectiveness checklist",
          "",
          "| Check | Target | Result | YES | NO | Note |",
          "|-------|--------|--------|-----|----|-----|",
          "| Distribution coverage (%) | ≥90 | | ☐ | ☐ | |",
          "| Return / action completion (%) | ≥95 | | ☐ | ☐ | |",
          "| Sample inspection done | — | | ☐ | ☐ | |",
          "| Customer confirmations | — | | ☐ | ☐ | |",
          "| CAPA required (FORM-CAPA-01) | — | | ☐ | ☐ | |",
          "",
          "**FSCA closure approval:** __________  **Date:** __________",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormCapa01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-CAPA-01",
    locale === "tr" ? "Düzeltici ve Önleyici Faaliyet (CAPA) Formu" : "Corrective and Preventive Action (CAPA) Form",
    "SOP-CAPA",
  );
  const body =
    locale === "tr"
      ? [
          "## Uygunsuzluk / olay",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| CAPA no | CAPA-________ |",
          "| Kaynak | ☐ İç denetim ☐ Şikâyet ☐ Üretim ☐ Tedarikçi ☐ PMS ☐ Diğer |",
          "| Kaynak ref | __________ |",
          "| Tarih | __________ |",
          "| Açıklama | __________ |",
          "",
          "## Analiz ve aksiyon",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Kök neden analizi | __________ |",
          "| Düzeltici faaliyet | __________ |",
          "| Önleyici faaliyet | __________ |",
          "| Sorumlu | __________ |",
          "| Hedef tarih | __________ |",
          "",
          "## Etkinlik doğrulama",
          "",
          "| Doğrulama yöntemi | Sonuç | EVET | HAYIR |",
          "|-------------------|-------|------|-------|",
          "| Aksiyon tamamlandı | | ☐ | ☐ |",
          "| Tekrar oluşmadı | | ☐ | ☐ |",
          "| Kayıtlar güncellendi | | ☐ | ☐ |",
          "",
          "**Kapanış onayı:** __________  **Tarih:** __________",
          "",
          "## Örnek",
          "",
          "| Alan | Örnek |",
          "|------|-------|",
          "| CAPA no | CAPA-2026-003 |",
          "| Kaynak | İç denetim minör bulgu |",
          "| Kaynak ref | REC-IA-01 / IA-F-001 |",
          "| Aksiyon | Talimat revizyon tarihi düzeltildi |",
        ].join("\n")
      : [
          "## Nonconformity / event",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| CAPA no | CAPA-________ |",
          "| Source | ☐ Internal audit ☐ Complaint ☐ Production ☐ Supplier ☐ PMS ☐ Other |",
          "| Source ref | __________ |",
          "| Date | __________ |",
          "| Description | __________ |",
          "",
          "## Analysis and action",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Root cause analysis | __________ |",
          "| Corrective action | __________ |",
          "| Preventive action | __________ |",
          "| Owner | __________ |",
          "| Target date | __________ |",
          "",
          "## Effectiveness verification",
          "",
          "| Verification method | Result | YES | NO |",
          "|---------------------|--------|-----|-----|",
          "| Action completed | | ☐ | ☐ |",
          "| No recurrence | | ☐ | ☐ |",
          "| Records updated | | ☐ | ☐ |",
          "",
          "**Closure approval:** __________  **Date:** __________",
          "",
          "## Example",
          "",
          "| Field | Example |",
          "|-------|---------|",
          "| CAPA no | CAPA-2026-003 |",
          "| Source | Internal audit minor finding |",
          "| Action | WI revision date corrected |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormCh01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-CH-01",
    locale === "tr" ? "Müşteri Şikâyet Formu" : "Customer Complaint Form",
    "SOP-CH",
  );
  const body =
    locale === "tr"
      ? [
          "## Şikâyet bilgileri",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Şikâyet no | CH-________ |",
          "| Alım tarihi | __________ |",
          "| Kaynak | ☐ Müşteri ☐ Distribütör ☐ Sağlık kurumu ☐ PMS ☐ İç ☐ Diğer |",
          "| Müşteri / kurum | __________ |",
          "| İletişim | __________ |",
          "| Ürün / model | __________ |",
          "| Lot / seri no | __________ |",
          "| UDI-DI (varsa) | __________ |",
          "| Şikâyet açıklaması | __________ |",
          "",
          "## İlk değerlendirme",
          "",
          "| Soru | EVET | HAYIR | Not |",
          "|------|------|-------|-----|",
          "| Hasta / kullanıcı emniyet riski var mı? | ☐ | ☐ | |",
          "| Vigilans bildirimi gerekli mi? (SOP-VG) | ☐ | ☐ | |",
          "| FSCA / danışma gerekli mi? (SOP-AN) | ☐ | ☐ | |",
          "| CAPA gerekli mi? (SOP-CAPA) | ☐ | ☐ | |",
          "",
          "**Değerlendiren:** __________  **Tarih:** __________",
          "",
          "> **CAPA gerekli değilse** şikâyet bu form ve kapanış bölümü ile tamamlanır.",
          "> **CAPA gerekliyse** ayrıca **FORM-CH-02** (şikâyet–CAPA bağlantısı) ve **FORM-CAPA-01** açılır.",
          "",
          "## Kapanış",
          "",
          "| Müşteri yanıtı tarihi | __________ |",
          "| Durum | ☐ Açık ☐ Kapatıldı |",
          "",
          "## Örnek (CAPA gerekmedi)",
          "",
          "| Alan | Örnek |",
          "|------|-------|",
          "| Şikâyet no | CH-2026-011 |",
          "| Ürün / lot | Steril set ST-100 / L20260228 |",
          "| CAPA gerekli | Hayır — tek seferlik kullanım hatası |",
          "| Durum | Kapatıldı |",
        ].join("\n")
      : [
          "## Complaint information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Complaint no | CH-________ |",
          "| Received date | __________ |",
          "| Source | ☐ Customer ☐ Distributor ☐ Healthcare ☐ PMS ☐ Internal ☐ Other |",
          "| Customer / institution | __________ |",
          "| Contact | __________ |",
          "| Product / model | __________ |",
          "| Lot / serial no | __________ |",
          "| UDI-DI (if applicable) | __________ |",
          "| Description | __________ |",
          "",
          "## Initial assessment",
          "",
          "| Question | YES | NO | Note |",
          "|----------|-----|-----|------|",
          "| Patient / user safety risk? | ☐ | ☐ | |",
          "| Vigilance report needed? (SOP-VG) | ☐ | ☐ | |",
          "| FSCA / advisory needed? (SOP-AN) | ☐ | ☐ | |",
          "| CAPA needed? (SOP-CAPA) | ☐ | ☐ | |",
          "",
          "**Assessed by:** __________  **Date:** __________",
          "",
          "> **If CAPA is not required**, close the complaint using this form only.",
          "> **If CAPA is required**, also open **FORM-CH-02** (complaint–CAPA linkage) and **FORM-CAPA-01**.",
          "",
          "## Closure",
          "",
          "| Customer response date | __________ |",
          "| Status | ☐ Open ☐ Closed |",
          "",
          "## Sample (no CAPA)",
          "",
          "| Field | Example |",
          "|-------|---------|",
          "| Complaint no | CH-2026-011 |",
          "| Product / lot | Sterile set ST-100 / L20260228 |",
          "| CAPA needed | No — single-use handling error |",
          "| Status | Closed |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormCh02(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-CH-02",
    locale === "tr"
      ? "Şikâyet–CAPA Bağlantı Formu (yalnızca CAPA gerekli olduğunda)"
      : "Complaint–CAPA Linkage Form (only when CAPA is required)",
    "SOP-CH",
  );
  const body =
    locale === "tr"
      ? [
          "> Bu form **yalnızca** FORM-CH-01 üzerinde CAPA gerekli görüldüğünde doldurulur. Her şikâyet için CAPA açılmaz.",
          "",
          "## Şikâyet referansı",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Şikâyet no (FORM-CH-01) | CH-________ |",
          "| Şikâyet değerlendirme tarihi | __________ |",
          "| Ürün / lot | __________ |",
          "",
          "## CAPA bağlantısı (FORM-CAPA-01)",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| CAPA no | CAPA-________ |",
          "| CAPA açılış tarihi | __________ |",
          "| CAPA durumu | ☐ Açık ☐ Kapalı |",
          "| CAPA sorumlusu | __________ |",
          "| Kök neden özeti | __________ |",
          "| Düzeltici / önleyici aksiyon özeti | __________ |",
          "| CAPA hedef tarih | __________ |",
          "| Etkinlik doğrulandı mı? | ☐ Evet ☐ Hayır ☐ Bekliyor |",
          "",
          "## Şikâyet kapanışı (CAPA ile)",
          "",
          "| Şikâyet durumu | ☐ İzlemede (CAPA açık) ☐ Kapatıldı (CAPA kapandı) |",
          "| Müşteri bilgilendirme tarihi | __________ |",
          "",
          "## Örnek",
          "",
          "| Alan | Örnek |",
          "|------|-------|",
          "| Şikâyet no | CH-2026-012 |",
          "| CAPA no | CAPA-2026-002 |",
          "| CAPA durumu | Açık — paketleme WI revizyonu |",
          "| Şikâyet durumu | İzlemede |",
        ].join("\n")
      : [
          "> Use this form **only** when CAPA is required on FORM-CH-01. Not every complaint opens a CAPA.",
          "",
          "## Complaint reference",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Complaint no (FORM-CH-01) | CH-________ |",
          "| Complaint assessment date | __________ |",
          "| Product / lot | __________ |",
          "",
          "## CAPA linkage (FORM-CAPA-01)",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| CAPA no | CAPA-________ |",
          "| CAPA opened date | __________ |",
          "| CAPA status | ☐ Open ☐ Closed |",
          "| CAPA owner | __________ |",
          "| Root cause summary | __________ |",
          "| Corrective / preventive action summary | __________ |",
          "| CAPA target date | __________ |",
          "| Effectiveness verified? | ☐ Yes ☐ No ☐ Pending |",
          "",
          "## Complaint closure (with CAPA)",
          "",
          "| Complaint status | ☐ Monitoring (CAPA open) ☐ Closed (CAPA closed) |",
          "| Customer notification date | __________ |",
          "",
          "## Sample",
          "",
          "| Field | Example |",
          "|-------|---------|",
          "| Complaint no | CH-2026-012 |",
          "| CAPA no | CAPA-2026-002 |",
          "| CAPA status | Open — packaging WI revision |",
          "| Complaint status | Monitoring |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormIa01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-IA-01",
    locale === "tr" ? "İç Tetkik Kontrol Listesi" : "Internal Audit Checklist",
    "SOP-IA",
  );
  const body =
    locale === "tr"
      ? [
          "## Tetkik bilgileri",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Tetkik no | IA-________ |",
          "| Tarih | __________ |",
          "| Denetçi | __________ |",
          "| Kapsam / alan | __________ |",
          "",
          "## Kontrol listesi",
          "",
          "| Madde | Uygun | Uygunsuz | Minör | Majör | Not |",
          "|-------|-------|----------|-------|-------|-----|",
          "| 4.2 Doküman kontrolü | ☐ | ☐ | ☐ | ☐ | |",
          "| 4.2.4 Kayıtların kontrolü | ☐ | ☐ | ☐ | ☐ | |",
          "| 6.2 İnsan kaynakları / yetkinlik | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.4 Satın alma ve tedarikçi | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.5 Üretim ve süreç kontrolü | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.5.8 İzlenebilirlik | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.6 Kalibrasyon / ölçüm cihazları | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.1 Geri bildirim (genel) | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.2 Şikâyet yönetimi | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.3 Yetkili kuruluş bildirimleri | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.4 İç tetkik süreci | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.5 CAPA | ☐ | ☐ | ☐ | ☐ | |",
        ].join("\n")
      : [
          "## Audit information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Audit no | IA-________ |",
          "| Date | __________ |",
          "| Lead auditor | __________ |",
          "| Scope / area | __________ |",
          "",
          "## Checklist",
          "",
          "| Item | OK | NC | Minor | Major | Note |",
          "|------|----|----|-------|-------|------|",
          "| 4.2 Document control | ☐ | ☐ | ☐ | ☐ | |",
          "| 4.2.4 Control of records | ☐ | ☐ | ☐ | ☐ | |",
          "| 6.2 Human resources / competence | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.4 Purchasing and suppliers | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.5 Production and process control | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.5.8 Traceability | ☐ | ☐ | ☐ | ☐ | |",
          "| 7.6 Calibration / measuring equipment | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.1 Feedback (general) | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.2 Complaint handling | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.3 Regulatory reporting | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.2.4 Internal audit process | ☐ | ☐ | ☐ | ☐ | |",
          "| 8.5 CAPA | ☐ | ☐ | ☐ | ☐ | |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormMr01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-MR-01",
    locale === "tr" ? "Yönetimin Gözden Geçirmesi Formu" : "Management Review Form",
    "SOP-MR",
  );
  const body =
    locale === "tr"
      ? [
          "## Toplantı bilgileri",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Toplantı tarihi | __________ |",
          "| Katılımcılar | __________ |",
          "",
          "## Girdiler (özet)",
          "",
          "| Girdi | Değerlendirme |",
          "|-------|---------------|",
          "| İç tetkik sonuçları | __________ |",
          "| Müşteri geri bildirimi | __________ |",
          "| CAPA durumu | __________ |",
          "| Kalite hedefleri | __________ |",
          "",
          "## Kararlar ve aksiyonlar",
          "",
          "| Karar | Sorumlu | Tarih |",
          "|-------|---------|-------|",
          "| | | |",
        ].join("\n")
      : [
          "## Meeting information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Meeting date | __________ |",
          "| Participants | __________ |",
          "",
          "## Inputs (summary)",
          "",
          "| Input | Assessment |",
          "|-------|------------|",
          "| Internal audit results | __________ |",
          "| Customer feedback | __________ |",
          "| CAPA status | __________ |",
          "| Quality objectives | __________ |",
          "",
          "## Decisions and actions",
          "",
          "| Decision | Owner | Date |",
          "|----------|-------|------|",
          "| | | |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormNcp01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-NCP-01",
    locale === "tr" ? "Uygunsuz Ürün Formu" : "Nonconforming Product Form",
    "SOP-NCP",
  );
  const body =
    locale === "tr"
      ? [
          "## Uygunsuzluk",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Kayıt no | NCP-________ |",
          "| Ürün / lot | __________ |",
          "| Adet | __________ |",
          "| Uygunsuzluk tanımı | __________ |",
          "| Ayırma / karantina | ☐ Yapıldı ☐ Yapılmadı |",
          "| Ayırma açıklaması | __________ |",
          "| Karar | ☐ Onarım ☐ İmha ☐ İade ☐ Yeniden işleme |",
          "",
          "## CAPA değerlendirmesi",
          "",
          "| Soru | EVET | HAYIR | Açıklama |",
          "|------|------|-------|----------|",
          "| CAPA gerekli mi? (SOP-CAPA) | ☐ | ☐ | |",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| CAPA ref | __________ |",
          "| CAPA id | __________ |",
        ].join("\n")
      : [
          "## Nonconformity",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Record no | NCP-________ |",
          "| Product / lot | __________ |",
          "| Quantity | __________ |",
          "| NC description | __________ |",
          "| Segregation / quarantine | ☐ Done ☐ Not done |",
          "| Segregation note | __________ |",
          "| Decision | ☐ Repair ☐ Scrap ☐ Return ☐ Rework |",
          "",
          "## CAPA assessment",
          "",
          "| Question | YES | NO | Note |",
          "|----------|-----|-----|------|",
          "| CAPA needed? (SOP-CAPA) | ☐ | ☐ | |",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| CAPA ref | __________ |",
          "| CAPA id | __________ |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormCc01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-CC-01",
    locale === "tr" ? "Değişiklik Talebi (CR) Formu" : "Change Request (CR) Form",
    "SOP-CC",
  );
  const body =
    locale === "tr"
      ? [
          "## Değişiklik bilgisi",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| CR no | CC-________ |",
          "| Tarih | __________ |",
          "| Başlatan | __________ |",
          "| Departman / süreç | __________ |",
          "| Değişiklik türü | ☐ Ürün ☐ Süreç ☐ KYS doküman ☐ Tedarikçi ☐ Yazılım ☐ Etiket/IFU ☐ Diğer |",
          "| Etkilenen ürün / model | __________ |",
          "| Etkilenen doküman / prosedür | __________ |",
          "| Değişiklik açıklaması | __________ |",
          "| Gerekçe / kaynak | ☐ CAPA ☐ İç tetkik ☐ Müşteri ☐ Regülasyon ☐ İyileştirme ☐ Diğer |",
          "| Kaynak ref | __________ |",
          "| Aciliyet | ☐ Düşük ☐ Orta ☐ Yüksek |",
          "| Geçici kontrol (varsa) | __________ |",
          "",
          "## Onay (CR açılışı)",
          "",
          "| Rol | Ad / imza | Tarih |",
          "|-----|-----------|-------|",
          "| Süreç sahibi | | |",
          "| Kalite Müdürü | | |",
          "",
          "## Örnek",
          "",
          "| Alan | Örnek |",
          "|------|-------|",
          "| CR no | CC-2026-007 |",
          "| Değişiklik | Steril set etiketinde UDI-DI güncellemesi |",
          "| Kaynak | Regülasyon / EUDAMED uyumu |",
        ].join("\n")
      : [
          "## Change information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| CR no | CC-________ |",
          "| Date | __________ |",
          "| Initiator | __________ |",
          "| Department / process | __________ |",
          "| Change type | ☐ Product ☐ Process ☐ QMS document ☐ Supplier ☐ Software ☐ Label/IFU ☐ Other |",
          "| Affected product / model | __________ |",
          "| Affected document / procedure | __________ |",
          "| Change description | __________ |",
          "| Rationale / source | ☐ CAPA ☐ Internal audit ☐ Customer ☐ Regulation ☐ Improvement ☐ Other |",
          "| Source ref | __________ |",
          "| Urgency | ☐ Low ☐ Medium ☐ High |",
          "| Interim control (if any) | __________ |",
          "",
          "## Approval (CR opening)",
          "",
          "| Role | Name / signature | Date |",
          "|------|------------------|------|",
          "| Process owner | | |",
          "| Quality Manager | | |",
          "",
          "## Sample",
          "",
          "| Field | Example |",
          "|-------|---------|",
          "| CR no | CC-2026-007 |",
          "| Change | Update UDI-DI on sterile set label |",
          "| Source | Regulation / EUDAMED alignment |",
        ].join("\n");
  return [h, body].join("\n\n");
}

export function buildFormCc02(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-CC-02",
    locale === "tr" ? "Değişiklik Etki Değerlendirme Formu" : "Change Impact Assessment Form",
    "SOP-CC",
  );
  const body =
    locale === "tr"
      ? [
          "## CR referansı",
          "",
          "| CR no | __________ | Etki değerlendiren | __________ | Tarih | __________ |",
          "",
          "## Etki alanları",
          "",
          "| Alan | Etkileniyor mu? | EVET | HAYIR | Açıklama / aksiyon |",
          "|------|-----------------|------|-------|---------------------|",
          "| KYS (prosedür, form, eğitim) | | ☐ | ☐ | |",
          "| Tasarım / spesifikasyon / V&V | | ☐ | ☐ | |",
          "| Risk yönetimi (ISO 14971) | | ☐ | ☐ | |",
          "| Üretim / proses validasyonu | | ☐ | ☐ | |",
          "| Tedarikçi / dış kaynak | | ☐ | ☐ | |",
          "| Etiket / IFU / teknik dosya | | ☐ | ☐ | |",
          "| Klinik değerlendirme / PMS | | ☐ | ☐ | |",
          "| NB bildirimi gerekliliği (ön) | | ☐ | ☐ | |",
          "",
          "**Özet risk değerlendirmesi:** _______________________________________________",
          "",
          "**FORM-CC-03 (önemli değişiklik) gerekli mi?** ☐ EVET ☐ HAYIR",
          "",
          "## Onay",
          "",
          "| Rol | Ad / imza | Tarih |",
          "|-----|-----------|-------|",
          "| Süreç sahibi | | |",
          "| Tasarım yetkilisi (uygulanırsa) | | |",
          "| Kalite Müdürü | | |",
        ].join("\n")
      : [
          "## CR reference",
          "",
          "| CR no | __________ | Assessed by | __________ | Date | __________ |",
          "",
          "## Impact areas",
          "",
          "| Area | Affected? | YES | NO | Description / action |",
          "|------|-----------|-----|-----|----------------------|",
          "| QMS (procedures, forms, training) | | ☐ | ☐ | |",
          "| Design / specification / V&V | | ☐ | ☐ | |",
          "| Risk management (ISO 14971) | | ☐ | ☐ | |",
          "| Manufacturing / process validation | | ☐ | ☐ | |",
          "| Supplier / outsourcing | | ☐ | ☐ | |",
          "| Label / IFU / technical file | | ☐ | ☐ | |",
          "| Clinical evaluation / PMS | | ☐ | ☐ | |",
          "| NB notification need (preliminary) | | ☐ | ☐ | |",
          "",
          "**Risk summary:** _______________________________________________",
          "",
          "**FORM-CC-03 (significant change) required?** ☐ YES ☐ NO",
          "",
          "## Approval",
          "",
          "| Role | Name / signature | Date |",
          "|------|------------------|------|",
          "| Process owner | | |",
          "| Design authority (if applicable) | | |",
          "| Quality Manager | | |",
        ].join("\n");
  return [h, body].join("\n\n");
}

export function buildFormCc03(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-CC-03",
    locale === "tr"
      ? "Önemli Değişiklik Değerlendirme Formu (MDCG 2020-3)"
      : "Significant Change Assessment Form (MDCG 2020-3)",
    "SOP-CC",
  );
  const body =
    locale === "tr"
      ? [
          "## CR ve cihaz bilgisi",
          "",
          "| CR no | __________ | Ürün / model | __________ |",
          "| Basic UDI-DI | __________ | MDR sınıfı | __________ |",
          "",
          "## Değişiklik tanımı",
          "",
          "| Soru | EVET | HAYIR | Not |",
          "|------|------|-------|-----|",
          "| Tasarım veya amaçlanan kullanım değişiyor mu? | ☐ | ☐ | |",
          "| Güvenlik / performans / fayda-risk etkisi var mı? | ☐ | ☐ | |",
          "| Geçiş hükümleri (Art. 120) kapsamında mı? | ☐ | ☐ | |",
          "",
          "## Karar",
          "",
          "| Karar | Seçim |",
          "|-------|-------|",
          "| Önemli değişiklik (significant) | ☐ |",
          "| Önemsiz değişiklik | ☐ |",
          "",
          "**Gerekçe:** _______________________________________________",
          "",
          "| NB görüşü / bildirimi | ☐ Gerekli ☐ Gerekli değil | Ref: __________ |",
          "",
          "## Onay",
          "",
          "| Rol | Ad / imza | Tarih |",
          "|-----|-----------|-------|",
          "| PRRC | | |",
          "| Tasarım yetkilisi | | |",
          "| Üst yönetim (önemli ise) | | |",
        ].join("\n")
      : [
          "## CR and device information",
          "",
          "| CR no | __________ | Product / model | __________ |",
          "| Basic UDI-DI | __________ | MDR class | __________ |",
          "",
          "## Change definition",
          "",
          "| Question | YES | NO | Note |",
          "|----------|-----|-----|------|",
          "| Design or intended purpose change? | ☐ | ☐ | |",
          "| Safety / performance / benefit-risk effect? | ☐ | ☐ | |",
          "| Under transitional provisions (Art. 120)? | ☐ | ☐ | |",
          "",
          "## Decision",
          "",
          "| Decision | Select |",
          "|----------|--------|",
          "| Significant change | ☐ |",
          "| Non-significant change | ☐ |",
          "",
          "**Rationale:** _______________________________________________",
          "",
          "| NB opinion / notification | ☐ Required ☐ Not required | Ref: __________ |",
          "",
          "## Approval",
          "",
          "| Role | Name / signature | Date |",
          "|------|------------------|------|",
          "| PRRC | | |",
          "| Design authority | | |",
          "| Top management (if significant) | | |",
        ].join("\n");
  return [h, body].join("\n\n");
}

export function buildFormHr01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-HR-01",
    locale === "tr" ? "Eğitim Kayıt Formu" : "Training Record Form",
    "SOP-HR",
  );
  const body =
    locale === "tr"
      ? [
          "## Eğitim bilgileri",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Kayıt no | TRN-________ |",
          "| Eğitim tarihi | __________ |",
          "| Eğitim konusu | __________ |",
          "| Süre | __________ |",
          "| Yer | __________ |",
          "| Eğitmen | __________ |",
          "| Eğitim yöntemi | ☐ Yüz yüze ☐ Online ☐ İş başında (OJT) ☐ Diğer |",
          "| Yöntem (diğer) | __________ |",
          "| İlgili prosedür / doküman | __________ |",
          "",
          "## Katılımcılar",
          "",
          "| No | Ad soyad | Departman | Katıldı | Değerlendirme sonucu | İmza |",
          "|----|----------|-----------|---------|---------------------|------|",
          "| 1 | | | ☐ | | |",
          "| 2 | | | ☐ | | |",
          "| 3 | | | ☐ | | |",
          "| 4 | | | ☐ | | |",
          "",
          "## Eğitim değerlendirmesi",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Değerlendirme yöntemi | ☐ Quiz ☐ Gözlem ☐ Sözlü ☐ Pratik uygulama ☐ Diğer |",
          "| Değerlendirme yöntemi (diğer) | __________ |",
          "| Değerlendirme özeti | __________ |",
          "| Eğitim etkin mi? | ☐ Evet | ☐ Hayır |",
          "| Etkinlik notu | __________ |",
          "",
          "**Onaylayan:** __________  **Tarih:** __________",
        ].join("\n")
      : [
          "## Training information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Record no | TRN-________ |",
          "| Training date | __________ |",
          "| Training topic | __________ |",
          "| Duration | __________ |",
          "| Location | __________ |",
          "| Trainer | __________ |",
          "| Training method | ☐ Face-to-face ☐ Online ☐ On-the-job (OJT) ☐ Other |",
          "| Method (other) | __________ |",
          "| Related procedure / document | __________ |",
          "",
          "## Participants",
          "",
          "| No | Name | Department | Attended | Assessment result | Signature |",
          "|----|------|------------|----------|-------------------|-----------|",
          "| 1 | | | ☐ | | |",
          "| 2 | | | ☐ | | |",
          "| 3 | | | ☐ | | |",
          "| 4 | | | ☐ | | |",
          "",
          "## Training evaluation",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Evaluation method | ☐ Quiz ☐ Observation ☐ Oral ☐ Practical ☐ Other |",
          "| Evaluation method (other) | __________ |",
          "| Evaluation summary | __________ |",
          "| Training effective? | ☐ Yes | ☐ No |",
          "| Effectiveness note | __________ |",
          "",
          "**Approved by:** __________  **Date:** __________",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormTr01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-TR-01",
    locale === "tr" ? "İzlenebilirlik / Lot Soy Ağacı Formu" : "Traceability / Lot Genealogy Form",
    "SOP-TR",
  );
  const body =
    locale === "tr"
      ? [
          "## Lot / seri bilgisi",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Ürün adı | __________ |",
          "| Model / REF | __________ |",
          "| Lot no | __________ |",
          "| Seri no | __________ |",
          "| UDI-PI | __________ |",
          "| Üretim tarihi | __________ |",
          "| Miktar | __________ |",
          "| Tedarikçi lot ref | __________ |",
          "",
          "## Dağıtım / geri çağırma",
          "",
          "| Müşteri / kanal | Lot | Adet | Sevkiyat tarihi |",
          "|-----------------|-----|------|-----------------|",
          "| | | | |",
        ].join("\n")
      : [
          "## Lot / serial information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Product name | __________ |",
          "| Model / REF | __________ |",
          "| Lot no | __________ |",
          "| Serial no | __________ |",
          "| UDI-PI | __________ |",
          "| Production date | __________ |",
          "| Quantity | __________ |",
          "| Supplier lot ref | __________ |",
          "",
          "## Distribution / recall",
          "",
          "| Customer / channel | Lot | Qty | Shipment date |",
          "|--------------------|-----|-----|---------------|",
          "| | | | |",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

export function buildFormMe01(locale: "tr" | "en"): string {
  const h = formHeader(
    locale,
    "FORM-ME-01",
    locale === "tr" ? "Kalibrasyon Kayıt Formu" : "Calibration Record Form",
    "SOP-ME",
  );
  const body =
    locale === "tr"
      ? [
          "## Ekipman bilgisi",
          "",
          "| Alan | Değer |",
          "|------|-------|",
          "| Ekipman no | __________ |",
          "| Ekipman adı | __________ |",
          "| Konum / süreç | __________ |",
          "| Ölçüm aralığı | __________ |",
          "| Kalibrasyon frekansı | __________ |",
          "",
          "## Kalibrasyon",
          "",
          "| Kalibrasyon tarihi | Sonraki kalibrasyon | Sertifika no | Sonuç |",
          "|--------------------|---------------------|--------------|-------|",
          "| __________ | __________ | __________ | Uygun ☐ / Uygun değil ☐ |",
          "",
          "**Out-of-tolerance CAPA ref:** __________",
        ].join("\n")
      : [
          "## Equipment information",
          "",
          "| Field | Value |",
          "|-------|-------|",
          "| Equipment no | __________ |",
          "| Equipment name | __________ |",
          "| Location / process | __________ |",
          "| Measurement range | __________ |",
          "| Calibration frequency | __________ |",
          "",
          "## Calibration",
          "",
          "| Calibration date | Next calibration | Certificate no | Result |",
          "|------------------|------------------|----------------|--------|",
          "| __________ | __________ | __________ | Pass ☐ / Fail ☐ |",
          "",
          "**Out-of-tolerance CAPA ref:** __________",
        ].join("\n");
  return [h, body, approvalBlock(locale)].join("\n\n");
}

const RULE_BASED_FORMS: Record<string, (locale: "tr" | "en") => string> = {
  "FORM-AN-01": buildFormAn01,
  "FORM-AN-02": buildFormAn02,
  "FORM-AN-03": buildFormAn03,
  "FORM-AN-04": buildFormAn04,
  "FORM-AN-05": buildFormAn05,
  "FORM-AN-06": buildFormAn06,
  "FORM-CAPA-01": buildFormCapa01,
  "FORM-CH-01": buildFormCh01,
  "FORM-CH-02": buildFormCh02,
  "FORM-IA-01": buildFormIa01,
  "FORM-MR-01": buildFormMr01,
  "FORM-NCP-01": buildFormNcp01,
  "FORM-CC-01": buildFormCc01,
  "FORM-CC-02": buildFormCc02,
  "FORM-CC-03": buildFormCc03,
  "FORM-HR-01": buildFormHr01,
  "FORM-TR-01": buildFormTr01,
  "FORM-ME-01": buildFormMe01,
};

export function getRuleBasedFormContent(
  code: string | null | undefined,
  locale: "tr" | "en",
  meta?: { title?: string; parentProcedureCode?: string | null; clauseRefs?: string | null },
): string | null {
  if (!code) return null;
  const c = code.trim().toUpperCase();
  const builder = RULE_BASED_FORMS[c];
  if (builder) return builder(locale);

  if (!c.startsWith("FORM-")) return null;
  return buildGenericFormContent({
    code: c,
    title: meta?.title ?? c,
    locale,
    parentProcedureCode: meta?.parentProcedureCode,
    clauseRefs: meta?.clauseRefs,
  });
}
