/** Rule-based procedure bodies with consistent section numbering (ISO SOP structure). */

import {
  buildSopCapaProcedure,
  buildSopDcProcedure,
  buildSopDdProcedure,
  buildSopIaProcedure,
  buildSopVgProcedure,
} from "@/lib/qms/critical-sop-templates";

export function buildSopCcProcedure(locale: "tr" | "en"): string {
  if (locale === "tr") {
    return [
      "## 1. Amaç",
      "",
      "Bu prosedür, ürün, süreç ve kalite yönetim sistemi değişikliklerinin EN ISO 13485, MDR Madde 120 ve MDCG 2020-3 kapsamında planlı şekilde yönetilmesini tanımlar.",
      "",
      "## 2. Kapsam",
      "",
      "Tasarım, üretim, tedarikçi, etiket/IFU, yazılım ve KYS doküman değişiklikleri için geçerlidir.",
      "",
      "## 3. Sorumluluklar",
      "",
      "- **Değişiklik başlatan:** CR açar ve gerekçeyi belgeler.",
      "- **Süreç sahibi / Kalite Müdürü:** Etki değerlendirmesi ve onay koordinasyonu.",
      "- **Tasarım yetkilisi:** Tasarım değişikliklerini onaylar.",
      "- **Düzenleyici işler (PRRC):** NB bildirimi ve MDR Art. 120 etkilerini değerlendirir.",
      "- **Üst yönetim:** Önemli değişiklikleri onaylar.",
      "",
      "## 4. Tanımlar",
      "",
      "**Değişiklik talebi (CR):** Kontrollü değişikliğin başlatıldığı kayıt.",
      "",
      "**Önemli değişiklik (significant change):** MDCG 2020-3 / MDR Art. 120 kapsamında tasarım veya amaçlanan kullanımdaki, güvenlik/performans/fayda-riski etkileyebilecek değişiklik.",
      "",
      "## 5. Prosedür",
      "",
      "### 5.1 Değişiklik Talebinin (CR) Başlatılması ve Kayıt",
      "",
      "5.1.1 Değişiklik ihtiyacı tanımlanır (iç tetkik, CAPA, müşteri, regülasyon, süreç iyileştirme).",
      "5.1.2 CR formu doldurulur: açıklama, gerekçe, etkilenen ürün/süreç/doküman.",
      "5.1.3 CR numarası verilir ve değişiklik kayıt defterine işlenir.",
      "",
      "### 5.2 Etki Değerlendirmesi",
      "",
      "5.2.1 **KYS etkisi** — etkilenen prosedürler, formlar, eğitim.",
      "5.2.2 **Tasarım ve geliştirme** — spesifikasyon, V&V, klinik değerlendirme ihtiyacı.",
      "5.2.3 **Risk yönetimi (ISO 14971)** — risk dosyası güncellemesi.",
      "5.2.4 **Üretim / proses** — validasyon, batch etkisi.",
      "5.2.5 **Tedarikçi / dış kaynak** — tedarikçi onayı.",
      "5.2.6 **Etiket / IFU / teknik dosya** — MDR teknik dokümantasyon.",
      "5.2.7 **NB bildirimi gerekliliği** — ön değerlendirme (PRRC).",
      "",
      "### 5.3 Önemli Değişiklik Değerlendirmesi (MDCG 2020-3 / MDR Art. 120)",
      "",
      "5.3.1 Önemli / önemsiz ayrımı yapılır; gerekçe kayıt altına alınır.",
      "5.3.2 Geçiş hükümleri (transitional provisions) dikkate alınır.",
      "5.3.3 NB görüşü / bildirimi gerekiyorsa PRRC koordine eder.",
      "5.3.4 Önemli değişiklik değerlendirme formu tamamlanır.",
      "",
      "### 5.4 Onay Süreci",
      "",
      "5.4.1 KYS doküman değişiklikleri — Kalite Müdürü onayı.",
      "5.4.2 Tasarım / ürün değişiklikleri — Tasarım yetkilisi + Kalite Müdürü.",
      "5.4.3 Önemli değişiklikler — Üst yönetim onayı.",
      "5.4.4 NB bildirimi tamamlandıktan sonra uygulama başlatılır.",
      "",
      "### 5.5 Uygulama",
      "",
      "5.5.1 Kontrollü dokümanlar revize edilir (SOP-DC).",
      "5.5.2 Etkilenen personel eğitilir; eğitim kaydı tutulur.",
      "5.5.3 Üretim / saha uygulaması planlanır.",
      "",
      "### 5.6 Doğrulama ve CR Kapanışı",
      "",
      "5.6.1 V&V / etkinlik doğrulaması yapılır.",
      "5.6.2 CR nesnel kanıtla kapatılır.",
      "",
      "## 6. Kayıtlar",
      "",
      "FORM-CC-01 (CR), FORM-CC-02 (etki analizi), FORM-CC-03 (önemli değişiklik), LIST-CC-01 (değişiklik kayıt defteri), DIA-CC-01 (süreç akışı), REC-CC-01 (örnek vaka); onay kayıtları, revizyon geçmişi, eğitim kayıtları.",
      "",
      "## 7. Referanslar",
      "",
      "EN ISO 13485:2016 (4.1.4, 7.3.9); MDR 2017/745 Madde 120; MDCG 2020-3; SOP-DC; SOP-RM.",
      "",
      "## 8. Revizyon geçmişi",
      "",
      "| Rev | Tarih | Açıklama |",
      "|-----|-------|----------|",
      "| 00 | [TBC] | İlk yayın |",
    ].join("\n");
  }

  return [
    "## 1. Purpose",
    "",
    "Defines planned management of product, process and QMS changes per EN ISO 13485, MDR Art. 120 and MDCG 2020-3.",
    "",
    "## 2. Scope",
    "",
    "Applies to design, manufacturing, supplier, labeling/IFU, software and QMS document changes.",
    "",
    "## 3. Responsibilities",
    "",
    "- **Change initiator:** Opens CR and documents rationale.",
    "- **Process owner / Quality Manager:** Impact assessment and approval coordination.",
    "- **Design authority:** Approves design changes.",
    "- **Regulatory (PRRC):** NB notification and MDR Art. 120 effects.",
    "- **Top management:** Approves significant changes.",
    "",
    "## 4. Definitions",
    "",
    "**Change request (CR):** Record initiating a controlled change.",
    "",
    "**Significant change:** Per MDCG 2020-3 / MDR Art. 120 — design or intended purpose change affecting safety/performance/benefit-risk.",
    "",
    "## 5. Procedure",
    "",
    "### 5.1 Change Request (CR) Initiation and Logging",
    "",
    "5.1.1 Define change need (audit, CAPA, customer, regulation, improvement).",
    "5.1.2 Complete CR form: description, rationale, affected product/process/document.",
    "5.1.3 Assign CR number and log in change register.",
    "",
    "### 5.2 Impact Assessment",
    "",
    "5.2.1 **QMS impact** — affected procedures, forms, training.",
    "5.2.2 **Design and development** — specification, V&V, clinical evaluation need.",
    "5.2.3 **Risk management (ISO 14971)** — risk file update.",
    "5.2.4 **Manufacturing / process** — validation, batch impact.",
    "5.2.5 **Supplier / outsourcing** — supplier approval.",
    "5.2.6 **Label / IFU / technical file** — MDR documentation.",
    "5.2.7 **NB notification need** — preliminary assessment (PRRC).",
    "",
    "### 5.3 Significant Change Assessment (MDCG 2020-3 / MDR Art. 120)",
    "",
    "5.3.1 Significant vs non-significant decision with documented rationale.",
    "5.3.2 Consider transitional provisions.",
    "5.3.3 NB opinion/notification when required — coordinated by PRRC.",
    "5.3.4 Complete significant change assessment form.",
    "",
    "### 5.4 Approval Process",
    "",
    "5.4.1 QMS document changes — Quality Manager approval.",
    "5.4.2 Design / product changes — Design authority + Quality Manager.",
    "5.4.3 Significant changes — Top management approval.",
    "5.4.4 Implementation starts after NB notification when applicable.",
    "",
    "### 5.5 Implementation",
    "",
    "5.5.1 Revise controlled documents (SOP-DC).",
    "5.5.2 Train affected personnel; retain training records.",
    "5.5.3 Plan production / field implementation.",
    "",
    "### 5.6 Verification and CR Closure",
    "",
    "5.6.1 Perform V&V / effectiveness verification.",
    "5.6.2 Close CR with objective evidence.",
    "",
    "## 6. Records",
    "",
    "FORM-CC-01 (CR), FORM-CC-02 (impact), FORM-CC-03 (significant change), LIST-CC-01 (change register), DIA-CC-01 (process flow), REC-CC-01 (sample case); approval records, revision history, training records.",
    "",
    "## 7. References",
    "",
    "EN ISO 13485:2016 (4.1.4, 7.3.9); MDR 2017/745 Art. 120; MDCG 2020-3; SOP-DC; SOP-RM.",
    "",
    "## 8. Revision history",
    "",
    "| Rev | Date | Description |",
    "|-----|------|-------------|",
    "| 00 | [TBC] | Initial issue |",
  ].join("\n");
}

const PROCEDURE_TEMPLATES: Record<string, (locale: "tr" | "en") => string> = {
  "SOP-CC": buildSopCcProcedure,
  "SOP-CAPA": buildSopCapaProcedure,
  "SOP-IA": buildSopIaProcedure,
  "SOP-VG": buildSopVgProcedure,
  "SOP-DC": buildSopDcProcedure,
  "SOP-DD": buildSopDdProcedure,
};

export function getRuleBasedProcedureContent(
  code: string | null | undefined,
  locale: "tr" | "en",
): string | null {
  if (!code) return null;
  const builder = PROCEDURE_TEMPLATES[code.trim().toUpperCase()];
  return builder ? builder(locale) : null;
}
