import type { ExportContext } from "./types";

export interface Manifest {
  generator: string;
  generatedAt: string;
  generatedBy: string;
  language: string;
  company: string;
  product?: string;
  deviceClass?: string;
  basicUdiDi?: string;
  contents: string[];
  linkedEvidence: {
    fileName: string;
    originalName: string | null;
    documentKind: string;
    linkedTarget: string;
    analysisSummary: string | null;
    checksumSha256: string | null;
  }[];
  disclaimer: string;
}

export const DISCLAIMER_TEXT =
  "This document was generated by MDRpilot for documentation support only. It does not constitute regulatory approval or legal advice. Final assessment must be performed by a qualified person and, where applicable, your Notified Body.";

export function buildManifest(ctx: ExportContext, contents: string[]): Manifest {
  return {
    generator: "MDRpilot",
    generatedAt: ctx.generatedAt.toISOString(),
    generatedBy: ctx.generatedBy,
    language: ctx.language,
    company: ctx.company.name,
    product: ctx.product?.name,
    deviceClass: ctx.product?.deviceClass,
    basicUdiDi: ctx.product?.basicUdiDi ?? undefined,
    contents,
    linkedEvidence: ctx.linkedEvidence.map((e) => ({
      fileName: e.fileName,
      originalName: e.originalName,
      documentKind: e.documentKind,
      linkedTarget: `${e.target}: ${e.targetLabel}`,
      analysisSummary: e.analysisSummary,
      checksumSha256: e.checksumSha256,
    })),
    disclaimer: DISCLAIMER_TEXT,
  };
}

export function manifestBuffer(manifest: Manifest): Buffer {
  return Buffer.from(JSON.stringify(manifest, null, 2), "utf-8");
}
