import "server-only";
import type { RiskLevel } from "@prisma/client";
import { prisma } from "@/lib/db";
import { assertCompanyAccess } from "@/lib/auth/guards";
import { riskLevelFromScore } from "@/lib/domain/constants";
import {
  defaultMitigations,
  finalResidualFromMitigations,
  parseMitigationsJson,
  resolveMitigations,
  riskScore,
  type RiskMitigationRow,
} from "@/lib/domain/risk-template";
import { computeRiskNumbersByCategory, isAutoGeneratedRiskNo } from "@/lib/domain/risk-category-codes";
import { buildRiskNarratives } from "@/lib/domain/risk-narratives";

export interface CreateRiskItemInput {
  sequenceNo?: number;
  riskNo?: string | null;
  hazard: string;
  sequenceOfEvents?: string | null;
  hazardousSituation?: string | null;
  harm?: string | null;
  riskSource?: string | null;
  initialSeverity: number;
  initialProbability: number;
  mitigations?: RiskMitigationRow[] | null;
  riskControlMeasure?: string | null;
  residualSeverity?: number;
  residualProbability?: number;
  residualAssessment?: string | null;
  benefitRiskJustification?: string | null;
  verificationOfControl?: string | null;
  linkedReferences?: string | null;
  tableERef?: string | null;
  /** Used for default benefit-risk narratives when assessments are omitted. */
  narrativeContext?: {
    intendedPurpose?: string | null;
    productName?: string | null;
    locale?: "tr" | "en";
  };
}

function nz(v: string | null | undefined) {
  return v && v.trim() ? v.trim() : null;
}

/** Heuristic: template Turkish vs short English AI snippets. */
function narrativeNeedsTurkishRefresh(text: string | null | undefined, locale: "tr" | "en"): boolean {
  if (locale !== "tr") return false;
  const t = text?.trim() ?? "";
  if (!t) return false;
  return /\b(the|clinical benefit|residual risk|acceptable|outweighs|benefit-risk|favourable|favorable)\b/i.test(
    t,
  );
}

function clampScore(n: number) {
  return Math.min(5, Math.max(1, Math.round(n)));
}

function normalizeMitigations(
  input: CreateRiskItemInput,
  residualSeverity?: number,
  residualProbability?: number,
): RiskMitigationRow[] {
  if (input.mitigations?.length) {
    return resolveMitigations({
      mitigations: input.mitigations.map((m) => ({
        category: m.category,
        actions: m.actions ?? "",
        residualSeverity: clampScore(m.residualSeverity),
        residualProbability: clampScore(m.residualProbability),
      })),
      residualSeverity: residualSeverity ?? 1,
      residualProbability: residualProbability ?? 1,
    });
  }
  const base = defaultMitigations(
    clampScore(residualSeverity ?? input.residualSeverity ?? 3),
    clampScore(residualProbability ?? input.residualProbability ?? 1),
  );
  const control = nz(input.riskControlMeasure);
  if (control) {
    const prod = base.find((m) => m.category === "PRODUCTION");
    if (prod) prod.actions = control;
  }
  return base;
}

async function assertProductAccess(companyId: string, productId: string) {
  const product = await prisma.product.findFirst({
    where: { id: productId, deletedAt: null },
    select: { id: true, companyId: true },
  });
  if (!product) return null;
  assertCompanyAccess(product.companyId, companyId);
  return product;
}

async function nextSequenceNo(productId: string): Promise<number> {
  const agg = await prisma.riskItem.aggregate({
    where: { productId },
    _max: { sequenceNo: true },
  });
  const max = agg._max.sequenceNo ?? 0;
  if (max > 0) return max + 1;
  const count = await prisma.riskItem.count({ where: { productId } });
  return count + 1;
}

function isAutoRiskNo(riskNo: string | null | undefined): boolean {
  return isAutoGeneratedRiskNo(riskNo);
}

/** Renumber FMEA rows 1…n and assign category-based risk codes (EH1, TS2, …). */
export async function resequenceProductRiskItems(productId: string): Promise<void> {
  const items = await prisma.riskItem.findMany({
    where: { productId },
    orderBy: { createdAt: "asc" },
    select: { id: true, riskNo: true, tableERef: true, riskSource: true },
  });
  if (items.length === 0) return;

  const riskNos = computeRiskNumbersByCategory(items);

  await prisma.$transaction(
    items.map((item, index) => {
      const sequenceNo = index + 1;
      return prisma.riskItem.update({
        where: { id: item.id },
        data: {
          sequenceNo,
          riskNo: riskNos.get(item.id) ?? item.riskNo,
        },
      });
    }),
  );
}

export async function ensureRiskSequences(productId: string): Promise<boolean> {
  const count = await prisma.riskItem.count({ where: { productId } });
  if (count === 0) return false;

  const items = await prisma.riskItem.findMany({
    where: { productId },
    select: { sequenceNo: true, riskNo: true },
  });

  const hasZero = items.some((i) => i.sequenceNo <= 0);
  const seqs = items.map((i) => i.sequenceNo);
  const hasDup = new Set(seqs).size !== seqs.length;
  const maxSeq = Math.max(...seqs);
  const needsSeqFix = hasZero || hasDup || maxSeq !== items.length;
  const hasLegacyRte = items.some((i) => /^RTE\d+$/i.test(i.riskNo?.trim() ?? ""));

  if (needsSeqFix || hasLegacyRte) {
    await resequenceProductRiskItems(productId);
    return true;
  }
  return false;
}

/** Force 1…n row numbers (e.g. after AI bulk add). */
export async function forceResequenceProductRiskItems(productId: string): Promise<void> {
  await resequenceProductRiskItems(productId);
}

function buildRiskData(productId: string, input: CreateRiskItemInput, sequenceNo: number) {
  const initialSeverity = clampScore(input.initialSeverity);
  const initialProbability = clampScore(input.initialProbability);
  const mitigations = normalizeMitigations(input, input.residualSeverity, input.residualProbability);
  const final = finalResidualFromMitigations(mitigations);
  const production = mitigations.find((m) => m.category === "PRODUCTION");
  const hazardousSituation = nz(input.hazardousSituation) ?? input.hazard.trim();
  const riskNo = nz(input.riskNo) ?? null;

  let residualAssessment = nz(input.residualAssessment);
  let benefitRiskJustification = nz(input.benefitRiskJustification);
  const locale = input.narrativeContext?.locale ?? "tr";
  const narratives = buildRiskNarratives(
    {
      hazardousSituation,
      harm: nz(input.harm),
      residualScore: final.score,
      residualLevel: final.level,
      intendedPurpose: input.narrativeContext?.intendedPurpose,
      productName: input.narrativeContext?.productName,
    },
    locale,
  );

  if (input.narrativeContext || locale === "tr") {
    residualAssessment = narratives.residualAssessment;
    benefitRiskJustification = narratives.benefitRiskJustification;
  } else if (!residualAssessment || !benefitRiskJustification) {
    if (!residualAssessment) residualAssessment = narratives.residualAssessment;
    if (!benefitRiskJustification) benefitRiskJustification = narratives.benefitRiskJustification;
  }

  return {
    productId,
    sequenceNo,
    riskNo,
    hazard:
      input.hazard.trim().slice(0, 500) ||
      hazardousSituation.slice(0, 500) ||
      riskNo ||
      hazardousSituation.slice(0, 500) ||
      "Risk",
    sequenceOfEvents: nz(input.sequenceOfEvents),
    hazardousSituation,
    harm: nz(input.harm),
    riskSource: nz(input.riskSource),
    tableERef: nz(input.tableERef),
    initialSeverity,
    initialProbability,
    initialRiskLevel: riskLevelFromScore(initialSeverity, initialProbability) as RiskLevel,
    riskControlMeasure: production?.actions ? production.actions : nz(input.riskControlMeasure),
    mitigations: mitigations as object[],
    residualSeverity: final.severity,
    residualProbability: final.probability,
    residualRiskLevel: final.level as RiskLevel,
    residualAssessment,
    benefitRiskJustification,
    verificationOfControl: nz(input.verificationOfControl),
    linkedReferences: nz(input.linkedReferences),
  };
}

export async function createRiskItem(
  companyId: string,
  productId: string,
  input: CreateRiskItemInput,
) {
  const product = await assertProductAccess(companyId, productId);
  if (!product) return null;

  const sequenceNo = input.sequenceNo && input.sequenceNo > 0 ? input.sequenceNo : await nextSequenceNo(productId);

  const created = await prisma.riskItem.create({
    data: buildRiskData(productId, input, sequenceNo),
    select: { id: true, hazard: true },
  });
  await resequenceProductRiskItems(productId);
  return created;
}

async function assertRiskItemAccess(
  companyId: string,
  productId: string,
  riskItemId: string,
) {
  const item = await prisma.riskItem.findFirst({
    where: { id: riskItemId, productId },
    select: { id: true, hazard: true, product: { select: { companyId: true } } },
  });
  if (!item) return null;
  assertCompanyAccess(item.product.companyId, companyId);
  return item;
}

export async function updateRiskItem(
  companyId: string,
  productId: string,
  riskItemId: string,
  input: CreateRiskItemInput,
) {
  const item = await assertRiskItemAccess(companyId, productId, riskItemId);
  if (!item) return null;

  const existing = await prisma.riskItem.findUnique({
    where: { id: riskItemId },
    select: { sequenceNo: true },
  });
  const sequenceNo = input.sequenceNo && input.sequenceNo > 0 ? input.sequenceNo : existing?.sequenceNo ?? 1;

  await prisma.riskItem.update({
    where: { id: riskItemId },
    data: buildRiskData(productId, input, sequenceNo),
    select: { id: true, hazard: true },
  });
  await resequenceProductRiskItems(productId);
  return prisma.riskItem.findUnique({
    where: { id: riskItemId },
    select: { id: true, hazard: true },
  });
}

export async function deleteRiskItem(
  companyId: string,
  productId: string,
  riskItemId: string,
) {
  const item = await assertRiskItemAccess(companyId, productId, riskItemId);
  if (!item) return null;

  await prisma.riskItem.delete({ where: { id: riskItemId } });
  await resequenceProductRiskItems(productId);
  return { id: item.id, hazard: item.hazard };
}

export async function bulkCreateRiskItems(
  companyId: string,
  productId: string,
  inputs: CreateRiskItemInput[],
) {
  const product = await assertProductAccess(companyId, productId);
  if (!product) return null;
  if (inputs.length === 0) return [];

  let seq = await nextSequenceNo(productId);
  const created = await prisma.$transaction(
    inputs.map((input) => {
      const sequenceNo = seq++;
      return prisma.riskItem.create({
        data: buildRiskData(productId, input, sequenceNo),
        select: { id: true, hazard: true },
      });
    }),
  );

  await resequenceProductRiskItems(productId);

  return created;
}

/** Fill missing per-row residual / benefit-risk text on existing FMEA rows. */
export async function backfillRiskItemNarratives(
  companyId: string,
  productId: string,
  locale: "tr" | "en" = "tr",
  overwrite = false,
): Promise<number> {
  const product = await assertProductAccess(companyId, productId);
  if (!product) return 0;

  const productRow = await prisma.product.findUnique({
    where: { id: productId },
    select: { name: true, intendedPurpose: true },
  });

  const items = await prisma.riskItem.findMany({
    where: { productId },
    orderBy: { sequenceNo: "asc" },
  });

  let updated = 0;
  for (const item of items) {
    const needsResidual =
      overwrite ||
      !item.residualAssessment?.trim() ||
      narrativeNeedsTurkishRefresh(item.residualAssessment, locale);
    const needsBenefit =
      overwrite ||
      !item.benefitRiskJustification?.trim() ||
      narrativeNeedsTurkishRefresh(item.benefitRiskJustification, locale);
    if (!needsResidual && !needsBenefit) continue;

    const mitigations = resolveMitigations({
      mitigations: parseMitigationsJson(item.mitigations),
      riskControlMeasure: item.riskControlMeasure,
      residualSeverity: item.residualSeverity,
      residualProbability: item.residualProbability,
    });
    const final = finalResidualFromMitigations(mitigations);
    const narratives = buildRiskNarratives(
      {
        hazardousSituation: item.hazardousSituation ?? item.hazard,
        harm: item.harm,
        residualScore: riskScore(final.severity, final.probability),
        residualLevel: final.level,
        intendedPurpose: productRow?.intendedPurpose,
        productName: productRow?.name,
      },
      locale,
    );

    await prisma.riskItem.update({
      where: { id: item.id },
      data: {
        residualAssessment: needsResidual ? narratives.residualAssessment : item.residualAssessment,
        benefitRiskJustification: needsBenefit ? narratives.benefitRiskJustification : item.benefitRiskJustification,
      },
    });
    updated++;
  }
  return updated;
}
