import {
  CLINICAL_DATABASE_CATALOG,
  databaseLabel,
  type LiteratureSearchData,
} from "@/lib/domain/clinical-literature-model";
import {
  buildIncludedLiteratureStudies,
  buildIncludedStudyClinicalRows,
  includedStudyRegistryId,
} from "@/lib/domain/clinical-included-studies-generator";
import { buildConsultantCerComment, registryEvidenceUrl } from "@/lib/domain/clinical-cer-premium";
import { buildRegulatorySummary, riskThemesSummary, type PreparedLiteratureInput } from "@/lib/domain/clinical-literature-shared";
import { newStudyId, type ClinicalStudyRecord } from "@/lib/domain/clinical-study-model";

export interface PreparedFindingsInput {
  locale: "tr" | "en";
  product: PreparedLiteratureInput["product"];
  literatureData?: LiteratureSearchData | null;
  risks: PreparedLiteratureInput["risks"];
}

function catalogGroup(id: string): "literature" | "regulatory" | null {
  return CLINICAL_DATABASE_CATALOG.find((d) => d.id === id)?.group ?? null;
}

function resolveIncludedStudies(input: PreparedFindingsInput): {
  studies: ReturnType<typeof buildIncludedLiteratureStudies>;
  total: number;
} {
  const { literatureData } = input;
  const total = literatureData?.prisma?.included ?? 0;
  if (!literatureData || total <= 0) {
    return { studies: [], total: 0 };
  }

  const stored = literatureData.includedStudies?.filter((s) => s.index > 0) ?? [];
  if (stored.length === total) {
    return { studies: stored, total };
  }

  const generated = buildIncludedLiteratureStudies(literatureData, input);
  return { studies: generated, total };
}

/** Consultant-grade draft rows — one row per PRISMA-included study + per registry + risk summary. */
export function buildPreparedClinicalStudies(input: PreparedFindingsInput): ClinicalStudyRecord[] {
  const { locale, literatureData, product } = input;
  const tr = locale === "tr";
  const searchDate = literatureData?.searchDate || new Date().toISOString().slice(0, 10);
  const searchQuery =
    literatureData?.searchQuery?.trim() ||
    `"${product.name}" AND (safety OR adverse OR performance)`;

  const selected = literatureData?.databases?.length
    ? literatureData.databases
    : CLINICAL_DATABASE_CATALOG.map((d) => d.id);

  const rows: ClinicalStudyRecord[] = [];
  const riskThemes = riskThemesSummary(input.risks, locale);

  const { studies: includedStudies, total: includedTotal } = resolveIncludedStudies(input);
  if (includedStudies.length > 0) {
    rows.push(
      ...buildIncludedStudyClinicalRows(includedStudies, {
        locale,
        total: includedTotal,
      }),
    );
  }

  for (const dbId of selected.filter((id) => catalogGroup(id) === "regulatory")) {
    const label = databaseLabel(dbId, locale);
    const registryRow = literatureData?.registryResults?.find((r) => r.registryId === dbId);
    const regQuery = registryRow?.query || searchQuery;
    rows.push({
      id: newStudyId(),
      registryId: dbId,
      source: label,
      design: tr ? "Ulusal kayıt / vigilans taraması" : "National registry / vigilance search",
      n: registryRow?.recordsScreened != null ? String(registryRow.recordsScreened) : "—",
      outcomes:
        registryRow?.summary ||
        buildRegulatorySummary(dbId, input, searchDate, regQuery),
      deviceSpecific: true,
      quality: "MED",
      notes: tr
        ? `MDRpilot taslak (${searchDate}). Canlı kayıt sorgusu ile doğrulanmalıdır.`
        : `MDRpilot draft (${searchDate}). Verify against live registry search.`,
      cerComment:
        registryRow?.cerComment ||
        buildConsultantCerComment({
          locale,
          registryId: dbId,
          sourceLabel: label,
          productName: product.name,
          riskThemes,
          status: registryRow?.status,
        }),
      evidenceUrl: registryRow?.evidenceUrl || registryEvidenceUrl(dbId),
    });
  }

  if (input.risks.length > 0) {
    rows.push({
      id: newStudyId(),
      registryId: "risk-alignment",
      source: tr ? "ISO 14971 risk dosyası — klinik değerlendirme özeti" : "ISO 14971 risk file — clinical evaluation summary",
      design: tr ? "Risk yönetimi dosyası" : "Risk management file",
      n: String(input.risks.length),
      outcomes: tr
        ? `FMEA'da ${input.risks.length} risk satırı klinik veri değerlendirmesine entegre edilmiştir. Kalan riskler fayda-risk analizinde kabul edilebilir bulunmuştur. Temalar: ${riskThemesSummary(input.risks, locale)}.`
        : `${input.risks.length} FMEA rows integrated into clinical data evaluation. Residual risks acceptable in benefit-risk analysis. Themes: ${riskThemesSummary(input.risks, locale)}.`,
      deviceSpecific: true,
      quality: "HIGH",
      notes: tr ? "Risk dosyasından otomatik özet" : "Auto summary from risk file",
    });
  }

  return rows;
}

function isAutoGeneratedRow(row: ClinicalStudyRecord): boolean {
  if (!row.registryId) return false;
  if (row.registryId.startsWith("lit-included-")) return true;
  if (row.registryId === "risk-alignment" || row.registryId === "literature-bundle") return true;
  if (catalogGroup(row.registryId) === "literature") return true;
  if (catalogGroup(row.registryId) === "regulatory") return true;
  return false;
}

/** Merge prepared rows: keep manual rows; replace all auto-generated rows. */
export function mergePreparedStudies(
  existing: ClinicalStudyRecord[],
  prepared: ClinicalStudyRecord[],
): ClinicalStudyRecord[] {
  const manual = existing.filter((r) => !isAutoGeneratedRow(r));
  const manualKeys = new Set(
    manual.map((r) => `${r.source.trim().toLowerCase()}|${r.design.trim().toLowerCase()}`),
  );
  const fromPrepared = prepared.filter(
    (r) => !manualKeys.has(`${r.source.trim().toLowerCase()}|${r.design.trim().toLowerCase()}`),
  );
  return [...manual, ...fromPrepared];
}

export { includedStudyRegistryId };
