/**
 * MDR Annex I GSPR evidence matrix — NB-grade checklist (~130 rows).
 * Includes detailed 23.2 / 23.3 / 23.4 sub-clauses per Regulation (EU) 2017/745.
 */
export type GsprTemplateRow = { gsprNo: string; requirementSummary: string };

const CH1: GsprTemplateRow[] = [
  { gsprNo: "1", requirementSummary: "Achieve intended performance; safe and effective; acceptable benefit-risk." },
  { gsprNo: "2", requirementSummary: "Reduce risks as far as possible without adversely affecting benefit-risk." },
  { gsprNo: "3", requirementSummary: "Establish, implement, document and maintain a risk management system." },
  { gsprNo: "4", requirementSummary: "Risk control: safe design, protective measures/alarms, information for safety." },
  { gsprNo: "5", requirementSummary: "Reduce use-error risks; ergonomic design for intended users and environment." },
  { gsprNo: "6", requirementSummary: "Performance not adversely affected during stated lifetime under normal use." },
  { gsprNo: "7", requirementSummary: "Characteristics not adversely affected during transport and storage." },
  { gsprNo: "8", requirementSummary: "Known/foreseeable risks and side-effects minimised and acceptable vs benefits." },
  { gsprNo: "9", requirementSummary: "Annex XVI products: risk no greater than analogous medical device." },
];

const CH2: GsprTemplateRow[] = [
  { gsprNo: "10.1", requirementSummary: "Chemical, physical and biological properties; materials, biocompatibility." },
  { gsprNo: "10.2", requirementSummary: "Minimise risks from contaminants and residues to patients and users." },
  { gsprNo: "10.3", requirementSummary: "Safe use with contacting materials/substances; medicinal product compatibility." },
  { gsprNo: "10.4.1", requirementSummary: "Reduce risks from released substances, particles, wear debris and residues." },
  { gsprNo: "10.4.2", requirementSummary: "CMR/endocrine substances >0.1% w/w: documented justification." },
  { gsprNo: "10.4.5", requirementSummary: "Label CMR/endocrine substances >0.1% w/w on device/packaging/IFU." },
  { gsprNo: "10.5", requirementSummary: "Reduce risks from unintentional ingress of substances into the device." },
  { gsprNo: "10.6", requirementSummary: "Reduce risks from released particles including nanomaterials." },
  { gsprNo: "11.1", requirementSummary: "Eliminate or reduce infection risks to patient, user and third parties." },
  { gsprNo: "11.2", requirementSummary: "Facilitate safe cleaning, disinfection and/or re-sterilisation where necessary." },
  { gsprNo: "11.3", requirementSummary: "Devices with specific microbial state remain in that state until use." },
  { gsprNo: "11.4", requirementSummary: "Devices delivered sterile remain sterile until packaging opened at point of use." },
  { gsprNo: "11.5", requirementSummary: "Devices labelled sterile processed and sterilised by validated methods." },
  { gsprNo: "11.6", requirementSummary: "Devices intended to be sterilised manufactured in controlled conditions." },
  { gsprNo: "11.7", requirementSummary: "Non-sterile packaging maintains integrity; suitable for indicated sterilisation." },
  { gsprNo: "11.8", requirementSummary: "Labelling distinguishes identical devices in sterile and non-sterile forms." },
  { gsprNo: "12.1", requirementSummary: "Medicinal substance with ancillary action: quality, safety and usefulness verified." },
  { gsprNo: "12.2", requirementSummary: "Absorbable/locally dispersed substances: safety per Directive 2001/83/EC Annex I." },
  { gsprNo: "13.1", requirementSummary: "Human-origin tissues/cells: donation, processing and viral safety per 2004/23/EC." },
  { gsprNo: "13.2", requirementSummary: "Animal-origin tissues/cells: sourcing, processing and viral safety; Reg. 722/2012." },
  { gsprNo: "13.3", requirementSummary: "Other non-viable biological substances: safe processing and viral inactivation." },
  { gsprNo: "14.1", requirementSummary: "Safe combination with other devices/equipment; connections minimise misconnection." },
  { gsprNo: "14.2", requirementSummary: "Reduce risks from physical features, environment, materials and interference." },
  { gsprNo: "14.3", requirementSummary: "Minimise fire or explosion risks during normal use and single-fault condition." },
  { gsprNo: "14.4", requirementSummary: "Adjustment, calibration and maintenance can be performed safely." },
  { gsprNo: "14.5", requirementSummary: "Interoperability and compatibility with other devices reliable and safe." },
  { gsprNo: "14.6", requirementSummary: "Measurement/monitoring scales designed per ergonomic principles." },
  { gsprNo: "14.7", requirementSummary: "Facilitate safe disposal of device and related waste substances." },
  { gsprNo: "15.1", requirementSummary: "Diagnostic/measuring function: sufficient accuracy, precision and stability." },
  { gsprNo: "15.2", requirementSummary: "Measurements expressed in legal units (Directive 80/181/EEC)." },
  { gsprNo: "16.1", requirementSummary: "Reduce radiation exposure compatible with intended purpose." },
  { gsprNo: "16.2", requirementSummary: "Intended hazardous radiation controllable with warnings/displays." },
  { gsprNo: "16.3", requirementSummary: "Reduce unintended, stray or scattered radiation exposure." },
  { gsprNo: "16.4", requirementSummary: "Ionising radiation per Directive 2013/59/Euratom; controllable dose." },
  { gsprNo: "17.1", requirementSummary: "Software/EPS: repeatability, reliability; single-fault risk reduction." },
  { gsprNo: "17.2", requirementSummary: "Software lifecycle, risk management, verification and validation (IEC 62304)." },
  { gsprNo: "17.3", requirementSummary: "Mobile platform software: account for screen size and use environment." },
  { gsprNo: "17.4", requirementSummary: "Minimum IT/hardware/network and cybersecurity requirements defined." },
  { gsprNo: "18.1", requirementSummary: "Non-implantable active devices: single-fault risk reduction." },
  { gsprNo: "18.2", requirementSummary: "Internal power supply: state indication and warning before critical level." },
  { gsprNo: "18.3", requirementSummary: "External power supply: alarm system for power failure." },
  { gsprNo: "18.4", requirementSummary: "Clinical parameter monitors: alarms for life-threatening situations." },
  { gsprNo: "18.5", requirementSummary: "Reduce electromagnetic interference generated by the device." },
  { gsprNo: "18.6", requirementSummary: "Adequate immunity to electromagnetic interference for intended use." },
  { gsprNo: "18.7", requirementSummary: "Protect against accidental electric shocks during use and single fault." },
  { gsprNo: "18.8", requirementSummary: "Protect against unauthorised access hampering intended function." },
  { gsprNo: "19.1", requirementSummary: "Active implantable: minimise energy, treatment and material ageing risks." },
  { gsprNo: "19.2", requirementSummary: "Active implantable: substance compatibility and energy source reliability." },
  { gsprNo: "19.3", requirementSummary: "Active implantable: identifiable for post-market risk measures." },
  { gsprNo: "19.4", requirementSummary: "Active implantable: unequivocal identification code readable if possible." },
  { gsprNo: "20.1", requirementSummary: "Protection against mechanical risks (movement, instability, moving parts)." },
  { gsprNo: "20.2", requirementSummary: "Reduce risks from vibration generated by the device." },
  { gsprNo: "20.3", requirementSummary: "Reduce risks from noise emitted by the device." },
  { gsprNo: "20.4", requirementSummary: "Energy supply terminals/connectors minimise connection risks." },
  { gsprNo: "20.5", requirementSummary: "Prevent fitting/refitting errors; indicate direction of movement where needed." },
  { gsprNo: "20.6", requirementSummary: "Accessible parts shall not reach dangerous temperatures under normal use." },
  { gsprNo: "21.1", requirementSummary: "Energy/substance delivery devices: accurate and maintainable dosing." },
  { gsprNo: "21.2", requirementSummary: "Prevent/indicate inadequate delivery; guard accidental hazardous release." },
  { gsprNo: "21.3", requirementSummary: "Controls and indicators clearly specified and understandable." },
  { gsprNo: "22.1", requirementSummary: "Lay-user devices perform appropriately for skills, means and environment." },
  { gsprNo: "22.2", requirementSummary: "Lay-user devices: safe use, reduced use-error and misinterpretation." },
  { gsprNo: "22.3", requirementSummary: "Lay-user devices: procedure to verify correct operation at time of use." },
];

const CH3_23_1: GsprTemplateRow[] = [
  { gsprNo: "23.1", requirementSummary: "General label/IFU requirements: medium, format, legibility, language, symbols." },
];

const CH3_23_2: GsprTemplateRow[] = [
  { gsprNo: "23.2.a", requirementSummary: "Label: device name or trade name." },
  { gsprNo: "23.2.b", requirementSummary: "Label: details to identify device, packaging contents and intended purpose." },
  { gsprNo: "23.2.c", requirementSummary: "Label: manufacturer name and registered place of business." },
  { gsprNo: "23.2.d", requirementSummary: "Label: authorised representative if manufacturer outside the Union." },
  { gsprNo: "23.2.e", requirementSummary: "Label: indication if device contains medicinal substance or biological material." },
  { gsprNo: "23.2.f", requirementSummary: "Label: CMR/endocrine substance labelling per Section 10.4.5 where applicable." },
  { gsprNo: "23.2.g", requirementSummary: "Label: lot number or serial number." },
  { gsprNo: "23.2.h", requirementSummary: "Label: UDI carrier per Article 27 and Annex VII Part C." },
  { gsprNo: "23.2.i", requirementSummary: "Label: expiry or safe-use time limit (year and month)." },
  { gsprNo: "23.2.j", requirementSummary: "Label: date of manufacture if no expiry date." },
  { gsprNo: "23.2.k", requirementSummary: "Label: special storage and/or handling conditions." },
  { gsprNo: "23.2.l", requirementSummary: "Label: sterile state and sterilisation method if supplied sterile." },
  { gsprNo: "23.2.m", requirementSummary: "Label: warnings/precautions requiring immediate user attention." },
  { gsprNo: "23.2.n", requirementSummary: "Label: single-use indication if applicable." },
  { gsprNo: "23.2.o", requirementSummary: "Label: reprocessed single-use indication, cycle count and limits." },
  { gsprNo: "23.2.p", requirementSummary: "Label: custom-made device statement if applicable." },
  { gsprNo: "23.2.q", requirementSummary: "Label: medical device indication; clinical investigation-only if applicable." },
  { gsprNo: "23.2.r", requirementSummary: "Label: qualitative/quantitative composition for absorbable body-orifice devices." },
  { gsprNo: "23.2.s", requirementSummary: "Label: serial/lot number for implantable devices." },
];

const CH3_23_3: GsprTemplateRow[] = [
  { gsprNo: "23.3.a", requirementSummary: "Sterile packaging: indication recognisable as sterile packaging." },
  { gsprNo: "23.3.b", requirementSummary: "Sterile packaging: declaration of sterile condition." },
  { gsprNo: "23.3.c", requirementSummary: "Sterile packaging: sterilisation method." },
  { gsprNo: "23.3.d", requirementSummary: "Sterile packaging: manufacturer name and address." },
  { gsprNo: "23.3.e", requirementSummary: "Sterile packaging: device description." },
  { gsprNo: "23.3.f", requirementSummary: "Sterile packaging: exclusively for clinical investigations if applicable." },
  { gsprNo: "23.3.g", requirementSummary: "Sterile packaging: custom-made device statement if applicable." },
  { gsprNo: "23.3.h", requirementSummary: "Sterile packaging: month and year of manufacture." },
  { gsprNo: "23.3.i", requirementSummary: "Sterile packaging: safe use/implant time limit (year and month)." },
  { gsprNo: "23.3.j", requirementSummary: "Sterile packaging: instruction if packaging damaged or opened before use." },
];

const CH3_23_4: GsprTemplateRow[] = [
  { gsprNo: "23.4.a", requirementSummary: "IFU: label particulars per 23.2 (a,c,e,f,k,l,n,r)." },
  { gsprNo: "23.4.b", requirementSummary: "IFU: intended purpose, indications, contra-indications, users and patient group." },
  { gsprNo: "23.4.c", requirementSummary: "IFU: clinical benefits where applicable." },
  { gsprNo: "23.4.d", requirementSummary: "IFU: link to SSCP per Article 32 where applicable." },
  { gsprNo: "23.4.e", requirementSummary: "IFU: performance characteristics." },
  { gsprNo: "23.4.f", requirementSummary: "IFU: software/accessory selection information for healthcare professionals." },
  { gsprNo: "23.4.g", requirementSummary: "IFU: residual risks, contra-indications and undesirable side-effects." },
  { gsprNo: "23.4.h", requirementSummary: "IFU: user specifications including measuring accuracy where applicable." },
  { gsprNo: "23.4.i", requirementSummary: "IFU: preparatory handling, sterilisation, assembly and calibration." },
  { gsprNo: "23.4.j", requirementSummary: "IFU: special facilities, training or qualifications required." },
  { gsprNo: "23.4.k", requirementSummary: "IFU: installation verification, maintenance, consumables and service safety." },
  { gsprNo: "23.4.l", requirementSummary: "IFU: actions if sterile packaging damaged or opened before use." },
  { gsprNo: "23.4.m", requirementSummary: "IFU: sterilisation instructions if supplied non-sterile for sterilisation before use." },
  { gsprNo: "23.4.n", requirementSummary: "IFU: reuse/reprocessing instructions and end-of-reuse criteria." },
  { gsprNo: "23.4.o", requirementSummary: "IFU: reconditioning under manufacturer responsibility if reusable." },
  { gsprNo: "23.4.p", requirementSummary: "IFU: single-use re-use risks from manufacturer's risk management file." },
  { gsprNo: "23.4.q", requirementSummary: "IFU: safe combination with other devices/equipment and known restrictions." },
  { gsprNo: "23.4.r", requirementSummary: "IFU: radiation nature, intensity and protection measures if device emits radiation." },
  { gsprNo: "23.4.s", requirementSummary: "IFU: warnings, precautions, contra-indications, limitations and patient briefing." },
  { gsprNo: "23.4.t", requirementSummary: "IFU: interaction profile for absorbable substance devices." },
  { gsprNo: "23.4.u", requirementSummary: "IFU: implantable device material/substance exposure information." },
  { gsprNo: "23.4.v", requirementSummary: "IFU: safe disposal instructions including infection and sharps hazards." },
  { gsprNo: "23.4.w", requirementSummary: "IFU: when lay user should consult a healthcare professional." },
  { gsprNo: "23.4.x", requirementSummary: "IFU: Annex XVI devices — absence of clinical benefit and use risks." },
  { gsprNo: "23.4.y", requirementSummary: "IFU: date of issue and revision identifier." },
  { gsprNo: "23.4.z", requirementSummary: "IFU: notice to report serious incidents to manufacturer and competent authority." },
  { gsprNo: "23.4.aa", requirementSummary: "IFU: implant patient information per Article 18." },
  { gsprNo: "23.4.ab", requirementSummary: "IFU: IT network, hardware and cybersecurity requirements for software devices." },
];

/** Consolidated parent rows replaced by detailed sub-clauses above. */
export const OBSOLETE_GSPR_NOS = ["10.4", "23.2", "23.3", "23.4"] as const;

export const GSPR_TEMPLATE: GsprTemplateRow[] = [
  ...CH1,
  ...CH2,
  ...CH3_23_1,
  ...CH3_23_2,
  ...CH3_23_3,
  ...CH3_23_4,
];

export const GSPR_TEMPLATE_COUNT = GSPR_TEMPLATE.length;
