import type { RiskLevel, RiskMitigationCategory, RiskMitigationRow } from "./types";
import { riskLevelFromScore } from "./constants";

import {
  computeRiskNumbersByCategory,
  displayRiskNo,
  formatCategoryRiskNo,
  isAutoGeneratedRiskNo,
  resolveRiskCategoryEn,
} from "./risk-category-codes";

export type { RiskMitigationCategory, RiskMitigationRow };

export const RISK_MITIGATION_CATEGORIES: RiskMitigationCategory[] = [
  "DESIGN",
  "PRODUCTION",
  "POST_MARKET",
];

export function riskScore(severity: number, probability: number): number {
  return severity * probability;
}

export function defaultMitigations(
  residualSeverity = 3,
  residualProbability = 1,
): RiskMitigationRow[] {
  return RISK_MITIGATION_CATEGORIES.map((category) => ({
    category,
    actions: "",
    residualSeverity,
    residualProbability,
  }));
}

export function parseMitigationsJson(raw: unknown): RiskMitigationRow[] | null {
  if (!Array.isArray(raw)) return null;
  const out: RiskMitigationRow[] = [];
  for (const row of raw) {
    if (!row || typeof row !== "object") continue;
    const r = row as Record<string, unknown>;
    const category = r.category as RiskMitigationCategory;
    if (!RISK_MITIGATION_CATEGORIES.includes(category)) continue;
    const residualSeverity = clampScore(Number(r.residualSeverity) || 3);
    const residualProbability = clampScore(Number(r.residualProbability) || 1);
    out.push({
      category,
      actions: typeof r.actions === "string" ? r.actions : "",
      residualSeverity,
      residualProbability,
    });
  }
  return out.length > 0 ? out : null;
}

function clampScore(n: number) {
  return Math.min(5, Math.max(1, Math.round(n)));
}

/** Normalize stored row into template mitigations (legacy single control → Üretim row). */
export function resolveMitigations(item: {
  mitigations?: RiskMitigationRow[] | null;
  riskControlMeasure?: string | null;
  residualSeverity: number;
  residualProbability: number;
}): RiskMitigationRow[] {
  if (item.mitigations?.length) {
    const byCat = new Map(item.mitigations.map((m) => [m.category, m]));
    return RISK_MITIGATION_CATEGORIES.map(
      (category) =>
        byCat.get(category) ?? {
          category,
          actions: "",
          residualSeverity: item.residualSeverity,
          residualProbability: item.residualProbability,
        },
    );
  }
  const base = defaultMitigations(item.residualSeverity, item.residualProbability);
  if (item.riskControlMeasure?.trim()) {
    const prod = base.find((m) => m.category === "PRODUCTION");
    if (prod) prod.actions = item.riskControlMeasure.trim();
  }
  return base;
}

export function finalResidualFromMitigations(mitigations: RiskMitigationRow[]) {
  const last = mitigations[mitigations.length - 1];
  const severity = last?.residualSeverity ?? 1;
  const probability = last?.residualProbability ?? 1;
  const level = riskLevelFromScore(severity, probability) as RiskLevel;
  return { severity, probability, level, score: riskScore(severity, probability) };
}

export function formatRiskNo(
  sequenceNo: number,
  riskNo?: string | null,
  categoryEn?: string | null,
) {
  if (riskNo?.trim() && !isAutoGeneratedRiskNo(riskNo)) return riskNo.trim();
  const category = categoryEn?.trim() || "General";
  return formatCategoryRiskNo(category, sequenceNo);
}

export { isAutoGeneratedRiskNo, computeRiskNumbersByCategory, displayRiskNo };

export function riskScoreCellClass(score: number): string {
  if (score >= 15) return "bg-red-200/80 text-red-950 dark:bg-red-950 dark:text-red-100";
  if (score >= 9) return "bg-orange-200/80 text-orange-950 dark:bg-orange-950 dark:text-orange-100";
  if (score >= 4) return "bg-yellow-200/80 text-yellow-950 dark:bg-yellow-950 dark:text-yellow-100";
  return "bg-emerald-100/80 text-emerald-950 dark:bg-emerald-950 dark:text-emerald-100";
}
