/** ISO/TR 24971:2020 Annex A — full question list (matches regulatory Ek A forms). */

import type { RiskAnnexARow } from "./risk-annex-a";

type RowSeed = Omit<RiskAnnexARow, "answer">;

export const ANNEX_A_SEEDS_TR: RowSeed[] = [
  { id: "A.2.1", no: "A.2.1", characteristic: "Amaçlanan kullanım", question: "Amaçlanan kullanım nedir ve tıbbi cihaz nasıl kullanılacaktır?" },
  { id: "A.2.2", no: "A.2.2", characteristic: "İmplant", question: "Tıbbi cihaz implant edilmek üzere tasarlanmış mıdır?" },
  { id: "A.2.3", no: "A.2.3", characteristic: "Hasta teması", question: "Tıbbi cihaz hasta veya diğer kişilerle temas halinde olacak mıdır?" },
  { id: "A.2.4", no: "A.2.4", characteristic: "Materyaller", question: "Tıbbi cihazda kullanılan veya cihazla temas halinde olan materyaller ve bileşenler nelerdir?" },
  { id: "A.2.5", no: "A.2.5", characteristic: "Enerji", question: "Hastaya enerji iletilir veya hastadan enerji çıkarılır mı?" },
  { id: "A.2.6", no: "A.2.6", characteristic: "Madde transferi", question: "Hastaya madde iletilir veya hastadan madde çıkarılır mı?" },
  { id: "A.2.7", no: "A.2.7", characteristic: "Biyolojik işleme", question: "Tıbbi cihaz biyolojik materyalleri yeniden kullanım, transfüzyon veya transplantasyon için işler mi?" },
  { id: "A.2.8", no: "A.2.8", characteristic: "Sterilite", question: "Tıbbi cihaz steril olarak tedarik edilir, kullanıcı tarafından sterilize edilir veya başka mikrobiyolojik kontroller uygulanır mı?" },
  { id: "A.2.9", no: "A.2.9", characteristic: "Temizlik / dezenfeksiyon", question: "Tıbbi cihaz kullanıcı tarafından rutin olarak temizlenip dezenfekte edilecek mi?" },
  { id: "A.2.10", no: "A.2.10", characteristic: "Hasta ortamı", question: "Tıbbi cihaz hasta ortamını değiştirir mi?" },
  { id: "A.2.11", no: "A.2.11", characteristic: "Ölçüm", question: "Ölçüm yapılır mı?" },
  { id: "A.2.12", no: "A.2.12", characteristic: "Yorumlama", question: "Tıbbi cihaz yorumlayıcı (interpretative) nitelik taşır mı?" },
  { id: "A.2.13", no: "A.2.13", characteristic: "Kombinasyon kullanımı", question: "Tıbbi cihaz diğer tıbbi cihazlar, ilaçlar veya tıbbi teknolojilerle birlikte kullanılmak üzere tasarlanmış mıdır?" },
  { id: "A.2.14", no: "A.2.14", characteristic: "İstenmeyen çıkışlar", question: "İstenmeyen enerji veya madde çıkışları var mı?" },
  { id: "A.2.15", no: "A.2.15", characteristic: "Çevresel etkilere duyarlılık", question: "Tıbbi cihaz çevresel etkilere duyarlı mıdır?" },
  { id: "A.2.16", no: "A.2.16", characteristic: "Çevreye etki", question: "Tıbbi cihaz çevreyi etkiler mi?" },
  { id: "A.2.17", no: "A.2.17", characteristic: "Sarf malzeme / aksesuar", question: "Tıbbi cihaz sarf malzemesi veya aksesuar gerektirir mi?" },
  { id: "A.2.18", no: "A.2.18", characteristic: "Bakım / kalibrasyon", question: "Bakım veya kalibrasyon gerekli mi?" },
  { id: "A.2.19", no: "A.2.19", characteristic: "Yazılım", question: "Tıbbi cihaz yazılım içerir mi?" },
  { id: "A.2.20", no: "A.2.20", characteristic: "Bilgi erişimi", question: "Tıbbi cihaz bilgi erişimine izin verir mi?" },
  { id: "A.2.21", no: "A.2.21", characteristic: "Kritik veri", question: "Tıbbi cihaz hasta bakımı için kritik veri depolar mı?" },
  { id: "A.2.22", no: "A.2.22", characteristic: "Raf ömrü", question: "Tıbbi cihazın sınırlı raf ömrü var mı?" },
  { id: "A.2.23", no: "A.2.23", characteristic: "Gecikmiş / uzun süreli etkiler", question: "Gecikmiş veya uzun süreli kullanım etkileri var mı?" },
  { id: "A.2.24", no: "A.2.24", characteristic: "Mekanik kuvvetler", question: "Tıbbi cihaz hangi mekanik kuvvetlere maruz kalacaktır?" },
  { id: "A.2.25", no: "A.2.25", characteristic: "Ömür belirleyicileri", question: "Tıbbi cihazın ömrünü ne belirler?" },
  { id: "A.2.26", no: "A.2.26", characteristic: "Tek kullanım", question: "Tıbbi cihaz tek kullanımlık olarak tasarlanmış mıdır?" },
  { id: "A.2.27", no: "A.2.27", characteristic: "İmha / bertaraf", question: "Güvenli devre dışı bırakma veya bertaraf gerekli mi?" },
  { id: "A.2.28", no: "A.2.28", characteristic: "Özel eğitim / beceri", question: "Kurulum veya kullanım özel eğitim veya beceri gerektirir mi?" },
  { id: "A.2.29", no: "A.2.29", characteristic: "Güvenlik bilgisi", question: "Güvenlik için bilgi nasıl sağlanacaktır?" },
  { id: "A.2.30", no: "A.2.30", characteristic: "Üretim süreçleri", question: "Yeni üretim süreçleri kurulacak veya devreye alılacak mı?" },
  { id: "A.2.31", no: "A.2.31", characteristic: "Kullanılabilirlik", question: "Başarılı uygulama kullanıcı arayüzünün kullanılabilirliğine bağlı mıdır?" },
  { id: "A.2.31.1", no: "A.2.31.1", characteristic: "Arayüz tasarımı", question: "Kullanıcı arayüzü tasarım özellikleri kullanım hatasına katkıda bulunabilir mi?" },
  { id: "A.2.31.2", no: "A.2.31.2", characteristic: "Dikkat dağınıklığı", question: "Dikkat dağınıklığı kullanım hatasına yol açabilecek ortamda kullanılır mı?" },
  { id: "A.2.31.3", no: "A.2.31.3", characteristic: "Bağlantı parçaları", question: "Bağlantı parçaları veya aksesuarları var mı?" },
  { id: "A.2.31.4", no: "A.2.31.4", characteristic: "Kontrol arayüzü", question: "Kontrol arayüzü var mı?" },
  { id: "A.2.31.5", no: "A.2.31.5", characteristic: "Bilgi gösterimi", question: "Tıbbi cihaz bilgi gösterir mi?" },
  { id: "A.2.31.6", no: "A.2.31.6", characteristic: "Menü kontrolü", question: "Tıbbi cihaz menü ile kontrol edilir mi?" },
  { id: "A.2.31.7", no: "A.2.31.7", characteristic: "Kullanıcı bilgi/beceri", question: "Başarılı kullanım kullanıcının bilgi, beceri ve yeteneklerine bağlı mıdır?" },
  { id: "A.2.31.8", no: "A.2.31.8", characteristic: "Özel ihtiyaçlar", question: "Özel ihtiyaçları olan kişiler tarafından kullanılacak mı?" },
  { id: "A.2.31.9", no: "A.2.31.9", characteristic: "Yetkisiz eylemler", question: "Kullanıcı arayüzü yetkisiz eylemleri başlatmak için kullanılabilir mi?" },
  { id: "A.2.32", no: "A.2.32", characteristic: "Alarm sistemi", question: "Tıbbi cihaz alarm sistemi içerir mi?" },
  { id: "A.2.33", no: "A.2.33", characteristic: "Yanlış kullanım", question: "Tıbbi cihaz hangi şekillerde yanlış kullanılabilir (kasıtlı veya kasıtsız)?" },
  { id: "A.2.34", no: "A.2.34", characteristic: "Taşınabilirlik", question: "Tıbbi cihaz mobil veya taşınabilir olarak tasarlanmış mıdır?" },
  { id: "A.2.35", no: "A.2.35", characteristic: "Temel performans", question: "Kullanım temel performansa (essential performance) bağlı mıdır?" },
  { id: "A.2.36", no: "A.2.36", characteristic: "Otonomi", question: "Tıbbi cihazın otonomi düzeyi var mı?" },
  { id: "A.2.37", no: "A.2.37", characteristic: "Klinik karar girdisi", question: "Tıbbi cihaz klinik karar belirlemede girdi olarak kullanılan çıktı üretir mi?" },
];

export const ANNEX_A_SEEDS_EN: RowSeed[] = [
  { id: "A.2.1", no: "A.2.1", characteristic: "Intended use", question: "What is the intended use and how is the medical device to be used?" },
  { id: "A.2.2", no: "A.2.2", characteristic: "Implantation", question: "Is the medical device intended to be implanted?" },
  { id: "A.2.3", no: "A.2.3", characteristic: "Patient contact", question: "Is the medical device intended to be in contact with the patient or other persons?" },
  { id: "A.2.4", no: "A.2.4", characteristic: "Materials", question: "What materials or components are utilized in or contact with the medical device?" },
  { id: "A.2.5", no: "A.2.5", characteristic: "Energy", question: "Is energy delivered to or extracted from the patient?" },
  { id: "A.2.6", no: "A.2.6", characteristic: "Substances", question: "Are substances delivered to or extracted from the patient?" },
  { id: "A.2.7", no: "A.2.7", characteristic: "Biological processing", question: "Are biological materials processed by the medical device for subsequent reuse, transfusion or transplantation?" },
  { id: "A.2.8", no: "A.2.8", characteristic: "Sterility", question: "Is the medical device supplied sterile or intended to be sterilized by the user, or are other microbiological controls applicable?" },
  { id: "A.2.9", no: "A.2.9", characteristic: "Cleaning / disinfection", question: "Is the medical device intended to be routinely cleaned and disinfected by the user?" },
  { id: "A.2.10", no: "A.2.10", characteristic: "Patient environment", question: "Does the medical device modify the patient environment?" },
  { id: "A.2.11", no: "A.2.11", characteristic: "Measurements", question: "Are measurements taken?" },
  { id: "A.2.12", no: "A.2.12", characteristic: "Interpretative", question: "Is the medical device interpretative?" },
  { id: "A.2.13", no: "A.2.13", characteristic: "Combination use", question: "Is the medical device intended for use in conjunction with other medical devices, medicines or other medical technologies?" },
  { id: "A.2.14", no: "A.2.14", characteristic: "Unwanted outputs", question: "Are there unwanted outputs of energy or substances?" },
  { id: "A.2.15", no: "A.2.15", characteristic: "Environmental susceptibility", question: "Is the medical device susceptible to environmental influences?" },
  { id: "A.2.16", no: "A.2.16", characteristic: "Environmental impact", question: "Does the medical device influence the environment?" },
  { id: "A.2.17", no: "A.2.17", characteristic: "Consumables / accessories", question: "Does the medical device require consumables or accessories?" },
  { id: "A.2.18", no: "A.2.18", characteristic: "Maintenance / calibration", question: "Is maintenance or calibration necessary?" },
  { id: "A.2.19", no: "A.2.19", characteristic: "Software", question: "Does the medical device contain software?" },
  { id: "A.2.20", no: "A.2.20", characteristic: "Information access", question: "Does the medical device allow access to information?" },
  { id: "A.2.21", no: "A.2.21", characteristic: "Critical data", question: "Does the medical device store data critical to patient care?" },
  { id: "A.2.22", no: "A.2.22", characteristic: "Shelf life", question: "Does the medical device have a restricted shelf life?" },
  { id: "A.2.23", no: "A.2.23", characteristic: "Delayed / long-term effects", question: "Are there any delayed or long-term use effects?" },
  { id: "A.2.24", no: "A.2.24", characteristic: "Mechanical forces", question: "To what mechanical forces will the medical device be subjected?" },
  { id: "A.2.25", no: "A.2.25", characteristic: "Lifetime determinants", question: "What determines the lifetime of the medical device?" },
  { id: "A.2.26", no: "A.2.26", characteristic: "Single use", question: "Is the medical device intended for single use?" },
  { id: "A.2.27", no: "A.2.27", characteristic: "Disposal", question: "Is safe decommissioning or disposal of the medical device necessary?" },
  { id: "A.2.28", no: "A.2.28", characteristic: "Special training / skills", question: "Does installation or use of the medical device require special training or special skills?" },
  { id: "A.2.29", no: "A.2.29", characteristic: "Safety information", question: "How will information for safety be provided?" },
  { id: "A.2.30", no: "A.2.30", characteristic: "Manufacturing processes", question: "Are new manufacturing processes established or introduced?" },
  { id: "A.2.31", no: "A.2.31", characteristic: "Usability", question: "Is successful application of the medical device dependent on the usability of the user interface?" },
  { id: "A.2.31.1", no: "A.2.31.1", characteristic: "Interface design", question: "Can the user interface design features contribute to use error?" },
  { id: "A.2.31.2", no: "A.2.31.2", characteristic: "Distractions", question: "Is the medical device used in an environment where distractions can cause use error?" },
  { id: "A.2.31.3", no: "A.2.31.3", characteristic: "Connecting parts", question: "Does the medical device have connecting parts or accessories?" },
  { id: "A.2.31.4", no: "A.2.31.4", characteristic: "Control interface", question: "Does the medical device have a control interface?" },
  { id: "A.2.31.5", no: "A.2.31.5", characteristic: "Information display", question: "Does the medical device display information?" },
  { id: "A.2.31.6", no: "A.2.31.6", characteristic: "Menu control", question: "Is the medical device controlled by a menu?" },
  { id: "A.2.31.7", no: "A.2.31.7", characteristic: "User knowledge / skills", question: "Is successful use dependent on a user's knowledge, skills and abilities?" },
  { id: "A.2.31.8", no: "A.2.31.8", characteristic: "Specific needs", question: "Will the medical device be used by persons with specific needs?" },
  { id: "A.2.31.9", no: "A.2.31.9", characteristic: "Unauthorised actions", question: "Can the user interface be used to initiate unauthorised actions?" },
  { id: "A.2.32", no: "A.2.32", characteristic: "Alarm system", question: "Does the medical device include an alarm system?" },
  { id: "A.2.33", no: "A.2.33", characteristic: "Misuse", question: "In what ways might the medical device be misused (deliberately or not)?" },
  { id: "A.2.34", no: "A.2.34", characteristic: "Mobility", question: "Is the medical device intended to be mobile or portable?" },
  { id: "A.2.35", no: "A.2.35", characteristic: "Essential performance", question: "Does the use of the medical device depend on essential performance?" },
  { id: "A.2.36", no: "A.2.36", characteristic: "Autonomy", question: "Does the medical device have a degree of autonomy?" },
  { id: "A.2.37", no: "A.2.37", characteristic: "Clinical action input", question: "Does the medical device produce an output that is used as an input in determining clinical action?" },
];
