/**
 * ISO/TR 24971 Tablo E.1 (tehlike) ve E.2 (tetikleyen olay) tohum satırları.
 * Kaynak: Yılmaz Bio TF.04-04.01 risk yönetim planı referansı (scripts/ref-risk-plan-extract.txt).
 */

export interface TableESeed {
  id: string;
  table: "E1" | "E2";
  categoryTr: string;
  categoryEn: string;
  groupTr?: string;
  groupEn?: string;
  hazardTr: string;
  hazardEn: string;
  defaultNoteTr?: string;
  defaultNoteEn?: string;
  /** product rule hints */
  naIfNonActive?: boolean;
  naIfNonSterile?: boolean;
  aIfSterile?: boolean;
  naIfNoSoftware?: boolean;
  naIfNonReusable?: boolean;
}

export const TABLE_E1_SEEDS: TableESeed[] = [
  // — Enerji Tehlikeleri —
  {
    id: "E1.001",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Elektromanyetik Enerji",
    groupEn: "Electromagnetic Energy",
    hazardTr: "Şebeke gerilimi",
    hazardEn: "Mains voltage",
    defaultNoteTr: "Cihaz aktif cihaz değildir.",
    defaultNoteEn: "The device is not an active device.",
    naIfNonActive: true,
  },
  {
    id: "E1.002",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Elektromanyetik Enerji",
    groupEn: "Electromagnetic Energy",
    hazardTr: "Kaçak akım",
    hazardEn: "Leakage current",
    defaultNoteTr: "Cihaz aktif cihaz değildir.",
    defaultNoteEn: "The device is not an active device.",
    naIfNonActive: true,
  },
  {
    id: "E1.003",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Elektromanyetik Enerji",
    groupEn: "Electromagnetic Energy",
    hazardTr: "Elektrikli alanlar",
    hazardEn: "Electric fields",
    defaultNoteTr: "Cihaz aktif cihaz değildir.",
    defaultNoteEn: "The device is not an active device.",
    naIfNonActive: true,
  },
  {
    id: "E1.004",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Elektromanyetik Enerji",
    groupEn: "Electromagnetic Energy",
    hazardTr: "Manyetik alanlar",
    hazardEn: "Magnetic fields",
    defaultNoteTr: "Cihaz aktif cihaz değildir.",
    defaultNoteEn: "The device is not an active device.",
    naIfNonActive: true,
  },
  {
    id: "E1.005",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Radyasyon enerjisi",
    groupEn: "Radiation energy",
    hazardTr: "İyonlaştırıcı radyasyon",
    hazardEn: "Ionizing radiation",
    defaultNoteTr: "İyonlaştırıcı radyasyon bulunmamaktadır.",
    defaultNoteEn: "There is no ionizing radiation.",
  },
  {
    id: "E1.006",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Radyasyon enerjisi",
    groupEn: "Radiation energy",
    hazardTr: "İyonlaştırıcı olmayan radyasyon",
    hazardEn: "Non-ionizing radiation",
    defaultNoteTr: "İyonlaştırıcı olmayan radyasyon bulunmamaktadır.",
    defaultNoteEn: "There is no non-ionizing radiation.",
  },
  {
    id: "E1.007",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Termal Enerji",
    groupEn: "Thermal Energy",
    hazardTr: "Yüksek sıcaklık",
    hazardEn: "High temperature",
    defaultNoteTr:
      "Paket mukavemet testlerinde belirtilen sıcaklığın üstüne çıkması sonucu sterilizasyonun bozulması çapraz enfeksiyona sebep olabilir.",
    defaultNoteEn:
      "Deterioration of sterilization as a result of exceeding the temperature specified in the package strength tests may cause cross-infection.",
    aIfSterile: true,
  },
  {
    id: "E1.008",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Termal Enerji",
    groupEn: "Thermal Energy",
    hazardTr: "Düşük sıcaklık",
    hazardEn: "Low temperature",
    defaultNoteTr:
      "Paket mukavemet testlerinde belirtilen sıcaklığın altında olması sonucu sterilizasyonun bozulması çapraz enfeksiyona sebep olabilir.",
    defaultNoteEn:
      "If the package is below the temperature specified in the strength tests, the deterioration of sterilization may cause cross-infection.",
    aIfSterile: true,
  },
  {
    id: "E1.009",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Yerçekim",
    hazardEn: "Gravity",
    defaultNoteTr:
      "Taşıma sırasında düşme sonrası paketin hasar görerek sterilizasyonu yitirmesi",
    defaultNoteEn:
      "Loss of sterilization by damaging the package after falling during transportation",
    aIfSterile: true,
  },
  {
    id: "E1.010",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Vibrasyon",
    hazardEn: "Vibration",
    defaultNoteTr: "Vibrasyon enerjisi bulunmamaktadır.",
    defaultNoteEn: "There is no vibration energy.",
  },
  {
    id: "E1.011",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Depolanan enerji",
    hazardEn: "Stored energy",
    defaultNoteTr: "Depolanan enerji bulunmamaktadır.",
    defaultNoteEn: "There is no stored energy.",
  },
  {
    id: "E1.012",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Hareketli parçalar",
    hazardEn: "Moving parts",
    defaultNoteTr: "Hareketli parça bulunmamaktadır.",
    defaultNoteEn: "There are no moving parts.",
  },
  {
    id: "E1.013",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Burulma, kesme, çekme kuvveti",
    hazardEn: "Torsion, shear or tensile force",
    defaultNoteTr: "Burulma, kesme, çekme kuvveti bulunmamaktadır.",
    defaultNoteEn: "There is no torsion, shear or tensile force.",
  },
  {
    id: "E1.014",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Hasta konumlandırılması ve hareketi",
    hazardEn: "Patient positioning and movement",
    defaultNoteTr:
      "Bükülme, kırılma ve gerilme uygulama esnasında daha fazla güç harcanması; ürün performansının bozulması yaşanabilir.",
    defaultNoteEn:
      "During bending, breaking and stretching, more power is consumed, and the performance of the product may deteriorate.",
  },
  {
    id: "E1.015",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Akustik enerji",
    groupEn: "Acoustic energy",
    hazardTr: "Akustik enerji",
    hazardEn: "Acoustic energy",
    defaultNoteTr: "Akustik enerji bulunmamaktadır.",
    defaultNoteEn: "There is no acoustic energy.",
  },
  {
    id: "E1.016",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Akustik enerji",
    groupEn: "Acoustic energy",
    hazardTr: "Ultrasonik enerji",
    hazardEn: "Ultrasonic energy",
    defaultNoteTr: "Akustik enerji bulunmamaktadır.",
    defaultNoteEn: "There is no acoustic energy.",
  },
  {
    id: "E1.017",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Akustik enerji",
    groupEn: "Acoustic energy",
    hazardTr: "İnfrasound enerji",
    hazardEn: "Infrasound energy",
    defaultNoteTr: "Akustik enerji bulunmamaktadır.",
    defaultNoteEn: "There is no acoustic energy.",
  },
  {
    id: "E1.018",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Akustik enerji",
    groupEn: "Acoustic energy",
    hazardTr: "Ses",
    hazardEn: "Sound",
    defaultNoteTr: "Akustik enerji bulunmamaktadır.",
    defaultNoteEn: "There is no acoustic energy.",
  },
  {
    id: "E1.019",
    table: "E1",
    categoryTr: "Enerji Tehlikeleri",
    categoryEn: "Energy Hazards",
    groupTr: "Mekanik Enerji",
    groupEn: "Mechanical Energy",
    hazardTr: "Yüksek basınçlı sıvı enjeksiyon",
    hazardEn: "High pressure liquid injection",
    defaultNoteTr: "Yüksek basınçlı sıvı enjeksiyon bulunmamaktadır.",
    defaultNoteEn: "There is no high pressure liquid injection.",
  },
  // — Biyolojik ve Kimyasal Tehlikeler —
  {
    id: "E1.020",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyolojik",
    groupEn: "Biological",
    hazardTr: "Bakteri",
    hazardEn: "Bacteria",
    defaultNoteTr:
      "Kullanım öncesi uygun olmayan sterilizasyon sonucu bakteri içerebilir.",
    defaultNoteEn:
      "Improper sterilization may cause bacteria containment before usage.",
    aIfSterile: true,
  },
  {
    id: "E1.021",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyolojik",
    groupEn: "Biological",
    hazardTr: "Virüsler",
    hazardEn: "Viruses",
    defaultNoteTr:
      "Kullanım öncesi uygun olmayan sterilizasyon sonucu virüs içerebilir.",
    defaultNoteEn:
      "Improper sterilization may cause virus containment before usage.",
    aIfSterile: true,
  },
  {
    id: "E1.022",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyolojik",
    groupEn: "Biological",
    hazardTr: "Diğer ajanlar (örnek, prionlar)",
    hazardEn: "Other agents (e.g. prions)",
    defaultNoteTr:
      "Kullanım öncesi uygun olmayan sterilizasyon sonucu diğer ajanları içerebilir.",
    defaultNoteEn:
      "Improper sterilization may cause other agents containment before usage.",
    aIfSterile: true,
  },
  {
    id: "E1.023",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyolojik",
    groupEn: "Biological",
    hazardTr: "Tekrarlayan ya da çapraz enfeksiyon",
    hazardEn: "Re- or cross-infection",
    defaultNoteTr:
      "Kullanım öncesi uygun olmayan sterilizasyon sonucu çapraz enfeksiyona sebep olabilir.",
    defaultNoteEn:
      "Improper sterilization may cause cross-infection before usage.",
    aIfSterile: true,
  },
  {
    id: "E1.024",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr:
      "Çevresel ya da ürün özelliğinden dolayı solunum yolunun, dokuların yabancı maddelere maruz kalması",
    hazardEn:
      "Exposure of airway, tissues, environment or property, e.g. to foreign materials",
    defaultNoteTr:
      "Uygun olmayan malzeme kullanımı dokularda ve vücutta biyouyumsuzluk yaratabilir.",
    defaultNoteEn:
      "The use of unsuitable materials can cause undesired biocompatibility effect and tissue in the body.",
  },
  {
    id: "E1.025",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Asitlik, alkalilik",
    hazardEn: "Acids or alkalis",
    defaultNoteTr: "Ürün kimyasal olarak aktif değildir.",
    defaultNoteEn: "Product is non-active as chemically.",
  },
  {
    id: "E1.026",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Kalıntı",
    hazardEn: "Residues",
    defaultNoteTr:
      "Başarısız yıkama durumunda ürün temizleme ajanları ve üretim kalıntıları bulunabilir.",
    defaultNoteEn:
      "Product cleaning agents or production residuals may be found because of fail of cleaning.",
  },
  {
    id: "E1.027",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Kontaminasyon",
    hazardEn: "Contaminates",
    defaultNoteTr:
      "Başarısız yıkama durumunda ürün temizleme ajanları ve üretim kalıntıları bulunabilir.",
    defaultNoteEn:
      "Product cleaning agents or production residuals may be found because of fail of cleaning.",
  },
  {
    id: "E1.028",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Katkı maddesi veya işleme yardımcıları",
    hazardEn: "Additives or processing aids",
    defaultNoteTr:
      "Üründe katkı maddesi yoktur; başarısız yıkama durumunda ürün temizleme ajanları ve üretim kalıntıları bulunabilir.",
    defaultNoteEn:
      "There is no additives on product; product cleaning agents or production residuals may be found because of fail of cleaning.",
  },
  {
    id: "E1.029",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Temizleme, dezenfeksiyon veya test ajanları",
    hazardEn: "Cleaning, disinfecting or testing agents",
    defaultNoteTr:
      "Başarısız yıkama durumunda ürün temizleme ajanları bulunabilir.",
    defaultNoteEn:
      "Product cleaning agents may be found because of fail of cleaning.",
  },
  {
    id: "E1.030",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Medikal gazlar",
    hazardEn: "Medical gasses",
    defaultNoteTr: "Üründe medikal gaz mevcut değildir.",
    defaultNoteEn: "There is no medical gases in product.",
  },
  {
    id: "E1.031",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Anestezik ürünler",
    hazardEn: "Anaesthetic products",
    defaultNoteTr: "Üründe anestezik ürünler mevcut değildir.",
    defaultNoteEn: "There is no anaesthetic products in product.",
  },
  {
    id: "E1.032",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Kimyasal",
    groupEn: "Chemical",
    hazardTr: "Bozunmuş ürünler",
    hazardEn: "Degradation products",
    defaultNoteTr: "Ürün bozunmamaktadır.",
    defaultNoteEn: "Product does not degrade.",
  },
  {
    id: "E1.033",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "Kimyasal bileşenlerin toksisitesi",
    hazardEn: "Physical and/or chemical information",
    defaultNoteTr:
      "Yüzey cihazları sınıfında deri ile temas etmektedir. Temas süresi 24 saatten azdır (A Sınıfı).",
    defaultNoteEn:
      "In the class of surface devices, it comes into contact with the skin. Contact time is less than 24 hours (Class A).",
  },
  {
    id: "E1.034",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "Allerji oluşumu / İritasyon / Hassasiyet",
    hazardEn: "Irritation or intracutaneous reactivity",
    defaultNoteTr:
      "Yüzey cihazları sınıfında deri ile temas etmektedir. Temas süresi 24 saatten azdır (A Sınıfı).",
    defaultNoteEn:
      "In the class of surface devices, it comes into contact with the skin. Contact time is less than 24 hours (Class A).",
  },
  {
    id: "E1.035",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "Pirojenite",
    hazardEn: "Pyrogenity",
    defaultNoteTr: "Biouyumluluk test matrisine göre kapsam dışı.",
    defaultNoteEn:
      "Out of scope according to the biocompatibility test matrix.",
  },
  {
    id: "E1.036",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "Sitoksisite",
    hazardEn: "Cytotoxicity",
    defaultNoteTr:
      "Yüzey cihazları sınıfında deri ile temas etmektedir. Temas süresi 24 saatten azdır (A Sınıfı).",
    defaultNoteEn:
      "In the class of surface devices, it comes into contact with the skin. Contact time is less than 24 hours (Class A).",
  },
  {
    id: "E1.037",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "Genotoksisite",
    hazardEn: "Genotoxicity",
    defaultNoteTr: "Biouyumluluk test matrisine göre kapsam dışı.",
    defaultNoteEn:
      "Out of scope according to the biocompatibility test matrix.",
  },
  {
    id: "E1.038",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "Subkronik toksisite / Akut sistemik toksisite",
    hazardEn: "Subacute toxicity / acute systemic toxicity",
    defaultNoteTr: "Biouyumluluk test matrisine göre kapsam dışı.",
    defaultNoteEn:
      "Out of scope according to the biocompatibility test matrix.",
  },
  {
    id: "E1.039",
    table: "E1",
    categoryTr: "Biyolojik ve Kimyasal Tehlikeler",
    categoryEn: "Biological and Chemical Hazards",
    groupTr: "Biyouyumluluk",
    groupEn: "Biocompatibility",
    hazardTr: "İmplantasyon",
    hazardEn: "Implantation",
    defaultNoteTr: "Biouyumluluk test matrisine göre kapsam dışı.",
    defaultNoteEn:
      "Out of scope according to the biocompatibility test matrix.",
  },
  // — Operasyonel Tehlikeler —
  {
    id: "E1.040",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Fonksiyon",
    groupEn: "Function",
    hazardTr: "Yanlış veya uygunsuz çıkış veya işlevsellik (fonksiyonellik)",
    hazardEn: "Incorrect or inappropriate output or functionality",
    defaultNoteTr:
      "Hatalı kullanım ya da üretim sonucu uygunsuz işlevsellik olabilir.",
    defaultNoteEn:
      "As a result of misuse or improper production it can be incorrect functionality.",
  },
  {
    id: "E1.041",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Fonksiyon",
    groupEn: "Function",
    hazardTr: "Yanlış ölçüm",
    hazardEn: "Incorrect measurement",
    defaultNoteTr: "Üründe ölçüm ile ilgili bir fonksiyon yoktur.",
    defaultNoteEn: "There is no function related to measurement of the product.",
  },
  {
    id: "E1.042",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Fonksiyon",
    groupEn: "Function",
    hazardTr: "Hatalı data transferi",
    hazardEn: "Erroneous data transfer",
    defaultNoteTr: "Ürün data transferi yapmamaktadır.",
    defaultNoteEn: "Product does not transfer data.",
    naIfNoSoftware: true,
  },
  {
    id: "E1.043",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Fonksiyon",
    groupEn: "Function",
    hazardTr: "İşlevselliğin bozulması veya kaybolması",
    hazardEn: "Loss or deterioration of function",
    defaultNoteTr:
      "Hatalı kullanım ya da üretim sonucu işlevsellik bozulabilir, kaybolabilir.",
    defaultNoteEn:
      "As a result of misuse or improper production function may be lost or deteriorated.",
  },
  {
    id: "E1.044",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Kullanım Hataları",
    groupEn: "Use error",
    hazardTr: "Dikkat hatası",
    hazardEn: "Attentional failure",
    defaultNoteTr: "Hekimde dikkat hatası oluşabilir.",
    defaultNoteEn: "Attention failure of physician may occur.",
  },
  {
    id: "E1.045",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Kullanım Hataları",
    groupEn: "Use error",
    hazardTr: "Bellek hatası",
    hazardEn: "Memory failure",
    defaultNoteTr: "Hekimde bellek hatası oluşabilir.",
    defaultNoteEn: "Memory failure of physician may occur.",
  },
  {
    id: "E1.046",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Kullanım Hataları",
    groupEn: "Use error",
    hazardTr: "Kural bazlı hata",
    hazardEn: "Rule-based failure",
    defaultNoteTr: "Cerrahi protokol uygulanmazsa hata oluşabilir.",
    defaultNoteEn: "Errors may occur if surgical protocol is not applied.",
  },
  {
    id: "E1.047",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Kullanım Hataları",
    groupEn: "Use error",
    hazardTr: "Bilgi bazlı hata",
    hazardEn: "Knowledge-based failure",
    defaultNoteTr: "Eksik veya yanlış bilgi hata oluşturabilir.",
    defaultNoteEn: "Missing or incorrect information may generate errors.",
  },
  {
    id: "E1.048",
    table: "E1",
    categoryTr: "Operasyonel Tehlikeler",
    categoryEn: "Operational Hazards",
    groupTr: "Kullanım Hataları",
    groupEn: "Use error",
    hazardTr: "Rutin ihlali",
    hazardEn: "Routine violation",
    defaultNoteTr: "Cerrahi protokol uygulanmazsa hata oluşabilir.",
    defaultNoteEn: "Errors may occur if surgical protocol is not applied.",
  },
  // — Bilgilendirme Tehlikeleri —
  {
    id: "E1.049",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Etiketleme",
    groupEn: "Labelling",
    hazardTr: "Eksik kullanım kılavuzu",
    hazardEn: "Incomplete instructions for use",
    defaultNoteTr: "Eksik kullanım kılavuzu hataya sebep olabilir.",
    defaultNoteEn: "Incomplete instructions for use may cause error.",
  },
  {
    id: "E1.050",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Etiketleme",
    groupEn: "Labelling",
    hazardTr: "Ürün performans özelliklerinin yetersiz tanımlanması",
    hazardEn: "Inadequate description of performance characteristics",
    defaultNoteTr:
      "Ürün performans özelliklerinin yetersiz tanımlanması hataya sebep olabilir.",
    defaultNoteEn:
      "Inadequate description of performance characteristics may cause error.",
  },
  {
    id: "E1.051",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Etiketleme",
    groupEn: "Labelling",
    hazardTr: "Amaçlanan kullanım özelliklerinin yetersiz anlatılması",
    hazardEn: "Inadequate specification of intended use",
    defaultNoteTr:
      "Amaçlanan kullanım özelliklerinin yetersiz anlatılması hatalı kullanıma sebep olabilir.",
    defaultNoteEn:
      "Inadequate specification of intended use may cause misuse.",
  },
  {
    id: "E1.052",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Etiketleme",
    groupEn: "Labelling",
    hazardTr: "Limitlerin yetersiz tanımlanması",
    hazardEn: "Inadequate disclosure of limitations",
    defaultNoteTr: "Spesifik limit mevcut değildir.",
    defaultNoteEn: "There is no specific limits.",
  },
  {
    id: "E1.053",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Çalıştırma Bilgileri",
    groupEn: "Operating instructions",
    hazardTr: "Kullanım öncesi kontrol özelliklerinin yetersizliği",
    hazardEn: "Inadequate specification of pre-use checks",
    defaultNoteTr:
      "Etiket ve kullanım kılavuzunun kontrol edilmemesi hataya sebep olabilir.",
    defaultNoteEn:
      "Not control of label and instruction for use may cause failure.",
  },
  {
    id: "E1.054",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Çalıştırma Bilgileri",
    groupEn: "Operating instructions",
    hazardTr: "Aşırı karmaşık kullanım bilgileri",
    hazardEn: "Over-complicated operating instructions",
    defaultNoteTr:
      "Aşırı karmaşık kullanım bilgileri hatalı kullanıma sebep olabilir.",
    defaultNoteEn:
      "Over-complicated operating instructions may cause improper use.",
  },
  {
    id: "E1.055",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Uyarlar",
    groupEn: "Warnings",
    hazardTr: "Yan etkiler, uyarılar",
    hazardEn: "Of side effects",
    defaultNoteTr:
      "Uyarı ve yan etki tanımlanmaması başarısızlığa sebep olabilir.",
    defaultNoteEn:
      "Non description of side effects and warnings may cause failure.",
  },
  {
    id: "E1.056",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Uyarlar",
    groupEn: "Warnings",
    hazardTr:
      "Tek kullanımlık tıbbi cihazın tekrar kullanılma riskleri (steril ürünler için)",
    hazardEn: "Of hazards likely with re-use of single-use medical devices",
    defaultNoteTr: "Ürün sterildir ve tekrar kullanılmamalıdır.",
    defaultNoteEn: "Product is sterile and is not re-usable.",
    aIfSterile: true,
    naIfNonReusable: true,
  },
  {
    id: "E1.057",
    table: "E1",
    categoryTr: "Bilgilendirme Tehlikeleri",
    categoryEn: "Information Hazards",
    groupTr: "Uyarlar",
    groupEn: "Warnings",
    hazardTr: "Servis ve bakım özellikleri",
    hazardEn: "Specification of service and maintenance",
    defaultNoteTr: "Ürün servis ve bakım gerektirmez.",
    defaultNoteEn: "Product does not need service or maintenance.",
  },
];

export const TABLE_E2_SEEDS: TableESeed[] = [
  // — Tamamlanmamış Gereksinimler —
  {
    id: "E2.001",
    table: "E2",
    categoryTr: "Tamamlanmamış Gereksinimler",
    categoryEn: "Incomplete requirements",
    groupTr: "Yetersiz Özellikler",
    groupEn: "Inadequate specification",
    hazardTr: "Tasarım parametreleri",
    hazardEn: "Design parameters",
    defaultNoteTr:
      "Tamamlanmamış tasarım parametreleri hataya sebep olabilir.",
    defaultNoteEn: "Incomplete design parameters can cause failure.",
  },
  {
    id: "E2.002",
    table: "E2",
    categoryTr: "Tamamlanmamış Gereksinimler",
    categoryEn: "Incomplete requirements",
    groupTr: "Yetersiz Özellikler",
    groupEn: "Inadequate specification",
    hazardTr: "Operasyon parametreleri",
    hazardEn: "Operating parameters",
    defaultNoteTr:
      "Tamamlanmamış uygulama parametreleri hataya sebep olabilir.",
    defaultNoteEn: "Incomplete application parameters can cause failure.",
  },
  {
    id: "E2.003",
    table: "E2",
    categoryTr: "Tamamlanmamış Gereksinimler",
    categoryEn: "Incomplete requirements",
    groupTr: "Yetersiz Özellikler",
    groupEn: "Inadequate specification",
    hazardTr: "Performans gereklilikleri",
    hazardEn: "Performance requirements",
    defaultNoteTr:
      "Tamamlanmamış performans gereklilikleri hataya sebep olabilir.",
    defaultNoteEn: "Incomplete performance requirements can cause failure.",
  },
  {
    id: "E2.004",
    table: "E2",
    categoryTr: "Tamamlanmamış Gereksinimler",
    categoryEn: "Incomplete requirements",
    groupTr: "Yetersiz Özellikler",
    groupEn: "Inadequate specification",
    hazardTr: "Hizmet gereklilikleri (bakım vb.)",
    hazardEn: "In-service requirements (e.g. maintenance, reprocessing)",
    defaultNoteTr:
      "Ürün kullanımdan önce kullanıcı tarafından temizlenmelidir. Tamamlanmamış temizlik gereklilikleri hataya sebep olabilir. Bakım gerektirmez.",
    defaultNoteEn:
      "Product must be cleaned prior to usage by user. Incomplete cleaning requirements can cause failure. Does not need maintenance.",
  },
  {
    id: "E2.005",
    table: "E2",
    categoryTr: "Tamamlanmamış Gereksinimler",
    categoryEn: "Incomplete requirements",
    groupTr: "Yetersiz Özellikler",
    groupEn: "Inadequate specification",
    hazardTr: "Raf ömrü",
    hazardEn: "Shelf life",
    defaultNoteTr: "Raf ömrü 3 yıldır.",
    defaultNoteEn: "Shelf life is 3 years.",
  },
  // — Üretim Prosesi —
  {
    id: "E2.006",
    table: "E2",
    categoryTr: "Üretim Prosesi",
    categoryEn: "Manufacturing Process",
    hazardTr: "Üretim prosesindeki değişikliklerin yetersiz kontrolü",
    hazardEn: "Insufficient control of changes in manufacturing processes",
    defaultNoteTr:
      "Üretim sürecindeki değişikliklerin yetersiz kontrolü hataya sebep olabilir.",
    defaultNoteEn:
      "Insufficient control of changes in manufacturing process may cause error.",
  },
  {
    id: "E2.007",
    table: "E2",
    categoryTr: "Üretim Prosesi",
    categoryEn: "Manufacturing Process",
    hazardTr: "Yetersiz hammadde / hammadde uyumluluğu kontrolü",
    hazardEn: "Insufficient control of raw material / raw materials compatibility",
    defaultNoteTr:
      "Yetersiz hammadde / hammadde uyumluluğu kontrolü üründe fonksiyon yetersizliği.",
    defaultNoteEn:
      "Insufficient control of raw materials compatibility may cause insufficient function of product.",
  },
  {
    id: "E2.008",
    table: "E2",
    categoryTr: "Üretim Prosesi",
    categoryEn: "Manufacturing Process",
    hazardTr: "Yetersiz üretim prosesi kontrolü",
    hazardEn: "Insufficient control of manufacturing processes",
    defaultNoteTr:
      "Yetersiz üretim prosesi kontrolü başarısızlığa sebep olabilir.",
    defaultNoteEn:
      "Insufficient control of manufacturing processes may cause failure.",
  },
  {
    id: "E2.009",
    table: "E2",
    categoryTr: "Üretim Prosesi",
    categoryEn: "Manufacturing Process",
    hazardTr: "Taşeron üreticilerin yetersiz kontrolü",
    hazardEn: "Insufficient control of subcontractors",
    defaultNoteTr:
      "Taşeron üreticilerin yetersiz kontrolü başarısızlığa sebep olabilir.",
    defaultNoteEn: "Insufficient control of subcontractors may cause error.",
  },
  // — Nakliye ve Depolama —
  {
    id: "E2.010",
    table: "E2",
    categoryTr: "Nakliye ve Depolama",
    categoryEn: "Transport and Storage",
    hazardTr: "Yetersiz ambalajlama",
    hazardEn: "Inadequate packaging",
    defaultNoteTr: "Bozulmuş ambalaj başarısızlığa sebep olabilir.",
    defaultNoteEn: "Corrupted packaging may cause failure.",
    aIfSterile: true,
  },
  {
    id: "E2.011",
    table: "E2",
    categoryTr: "Nakliye ve Depolama",
    categoryEn: "Transport and Storage",
    hazardTr: "Kontaminasyon veya bozulma",
    hazardEn: "Contamination or deterioration",
    defaultNoteTr: "Ürün non steril olarak satılmaktadır.",
    defaultNoteEn: "Product is sold as non sterile.",
    naIfNonSterile: true,
  },
  {
    id: "E2.012",
    table: "E2",
    categoryTr: "Nakliye ve Depolama",
    categoryEn: "Transport and Storage",
    hazardTr: "Uygunsuz çevre koşulları",
    hazardEn: "Inappropriate environmental conditions",
    defaultNoteTr:
      "Ürün steril olarak satılmaktadır. Saklama koşulunu ambalaj belirler.",
    defaultNoteEn:
      "Product is sold as sterile. Package defines the specific condition for storage.",
    aIfSterile: true,
  },
  // — Çevresel Faktörler —
  {
    id: "E2.013",
    table: "E2",
    categoryTr: "Çevresel Faktörler",
    categoryEn: "Environmental factors",
    hazardTr: "Fiziksel (sıcaklık, basınç, zaman)",
    hazardEn: "Physical (e.g. heat, pressure, time)",
    defaultNoteTr: "Uygun materyal kullanılmaması soruna yol açar.",
    defaultNoteEn: "Using unsuitable material cause problem.",
  },
  {
    id: "E2.014",
    table: "E2",
    categoryTr: "Çevresel Faktörler",
    categoryEn: "Environmental factors",
    hazardTr: "Kimyasal (korozyon, bozulma, kontaminasyon)",
    hazardEn: "Chemical (e.g. corrosion, degradation, contamination)",
    defaultNoteTr: "Uygun materyal kullanılmaması soruna yol açar.",
    defaultNoteEn: "Using unsuitable material cause problem.",
  },
  {
    id: "E2.015",
    table: "E2",
    categoryTr: "Çevresel Faktörler",
    categoryEn: "Environmental factors",
    hazardTr: "Elektromanyetik alanlar",
    hazardEn: "Electromagnetic fields (e.g. susceptibility to electromagnetic disturbance)",
    defaultNoteTr: "Elektromanyetik alanlar ürünü etkilemez.",
    defaultNoteEn: "Electromagnetic fields do not affect product.",
    naIfNonActive: true,
  },
  {
    id: "E2.016",
    table: "E2",
    categoryTr: "Çevresel Faktörler",
    categoryEn: "Environmental factors",
    hazardTr: "Yetersiz besleme enerjisi",
    hazardEn: "Inadequate supply of power",
    defaultNoteTr: "Enerji kaynağı ile çalışmaz.",
    defaultNoteEn: "No energy supply.",
    naIfNonActive: true,
  },
  {
    id: "E2.017",
    table: "E2",
    categoryTr: "Çevresel Faktörler",
    categoryEn: "Environmental factors",
    hazardTr: "Yetersiz soğutucu beslemesi",
    hazardEn: "Inadequate supply of coolant",
    defaultNoteTr: "Ürün bir soğutucu ile beslenmemektedir.",
    defaultNoteEn: "Product is not supplied by coolant.",
  },
  // — Temizlik, dezenfeksiyon, sterilizasyon —
  {
    id: "E2.018",
    table: "E2",
    categoryTr: "Temizlik, dezenfeksiyon, sterilizasyon",
    categoryEn: "Cleaning, disinfection and sterilization",
    hazardTr:
      "Yetersiz valide edilmiş temizlik, dezenfeksiyon, sterilizasyon prosedürleri",
    hazardEn:
      "Inadequately validated cleaning, disinfection and sterilization procedures",
    defaultNoteTr:
      "Yetersiz valide edilmiş temizlik, dezenfeksiyon ve sterilizasyon prosedürleri enfeksiyona sebep olabilir.",
    defaultNoteEn:
      "Inadequately validated cleaning, disinfection and sterilization procedures may cause infection.",
    aIfSterile: true,
  },
  {
    id: "E2.019",
    table: "E2",
    categoryTr: "Temizlik, dezenfeksiyon, sterilizasyon",
    categoryEn: "Cleaning, disinfection and sterilization",
    hazardTr:
      "Temizlik, dezenfeksiyon, sterilizasyon konularının yetersiz yürütülmesi",
    hazardEn: "Inadequate conduct of cleaning, disinfection and sterilization",
    defaultNoteTr:
      "Yetersiz temizlik, dezenfeksiyon ve sterilizasyon enfeksiyona sebep olur.",
    defaultNoteEn:
      "Inadequate cleaning, disinfection and sterilization may cause infections.",
    aIfSterile: true,
  },
  // — Bertaraf —
  {
    id: "E2.020",
    table: "E2",
    categoryTr: "Bertaraf",
    categoryEn: "Disposal and scrapping",
    hazardTr: "Ürün bertarafı ile ilgili yetersiz bilgi",
    hazardEn: "Inadequate information for product disposal",
    defaultNoteTr:
      "Ürün bertarafı ile ilgili uyarı olmaması mevcut düzenlemelere aykırı durum oluşturabilir.",
    defaultNoteEn:
      "Lack of warning about the product disposal may create contrary to the existing regulations.",
  },
  {
    id: "E2.021",
    table: "E2",
    categoryTr: "Bertaraf",
    categoryEn: "Disposal and scrapping",
    hazardTr: "Kullanım hatası",
    hazardEn: "Usage error",
    defaultNoteTr:
      "Ürün bertarafı ile ilgili uyarı olmaması mevcut düzenlemelere aykırı durum oluşturabilir.",
    defaultNoteEn:
      "Lack of warning about the product disposal may create contrary to the existing regulations.",
  },
  // — Formülasyon —
  {
    id: "E2.022",
    table: "E2",
    categoryTr: "Formülasyon",
    categoryEn: "Formulation",
    hazardTr: "Biyolojik bozunma",
    hazardEn: "Biodegradation",
    defaultNoteTr: "Ürün biyolojik olarak bozunmaz.",
    defaultNoteEn: "Non biodegradable products.",
  },
  {
    id: "E2.023",
    table: "E2",
    categoryTr: "Formülasyon",
    categoryEn: "Formulation",
    hazardTr: "Biyouyumluluk",
    hazardEn: "Biocompatibility",
    defaultNoteTr: "Ürün vücutla temas etmektedir.",
    defaultNoteEn: "Product contacts with body.",
  },
  {
    id: "E2.024",
    table: "E2",
    categoryTr: "Formülasyon",
    categoryEn: "Formulation",
    hazardTr: "Ürün spesifikasyonları ile ilgili yetersiz bilgi",
    hazardEn: "Inadequate information on product specification",
    defaultNoteTr:
      "Ürün spesifikasyonları ile ilgili yetersiz bilgi hatalı kullanıma sebep olabilir.",
    defaultNoteEn:
      "No information or inadequate specification provided can cause improper use.",
  },
  {
    id: "E2.025",
    table: "E2",
    categoryTr: "Formülasyon",
    categoryEn: "Formulation",
    hazardTr: "Yanlış formülasyondan kaynaklı tehlikeler",
    hazardEn: "Hazards based on wrong formulation",
    defaultNoteTr:
      "Üründe yanlış kullanıma sebep olacak formülasyon mevcut değildir.",
    defaultNoteEn:
      "There is no formulation in products that may cause improper use.",
  },
  {
    id: "E2.026",
    table: "E2",
    categoryTr: "Formülasyon",
    categoryEn: "Formulation",
    hazardTr: "Kullanım hatası",
    hazardEn: "Usage error",
    defaultNoteTr:
      "Üründe yanlış kullanıma sebep olacak formülasyon mevcut değildir.",
    defaultNoteEn:
      "There is no formulation in products that may cause improper use.",
  },
  // — İnsan Faktörü —
  {
    id: "E2.027",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Eksik veya karmaşık kullanım kılavuzu",
    hazardEn: "Confusing or missing instructions for use",
    defaultNoteTr:
      "Eksik veya karmaşık kullanım kılavuzu yanlış kullanıma sebep olabilir.",
    defaultNoteEn:
      "Confusing or missing instructions for use may cause improper use.",
  },
  {
    id: "E2.028",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Karmaşık ve yanıltıcı kontrol sistemi",
    hazardEn: "Complex or confusing control system",
    defaultNoteTr: "Üründe kontrol sistemi mevcut değildir.",
    defaultNoteEn: "There is no control system in product.",
    naIfNoSoftware: true,
  },
  {
    id: "E2.029",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Belirsiz veya açık olmayan cihaz durumu",
    hazardEn: "Ambiguous or unclear device state",
    defaultNoteTr:
      "Hatalı veya eksik etiketleme yanlış kullanıma sebep olabilir.",
    defaultNoteEn: "Incorrect or incomplete labelling may cause improper use.",
  },
  {
    id: "E2.030",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr:
      "Belirsiz veya açık olmayan bir şekilde ayarların, ölçmelerin veya diğer bilgilerin sunumu",
    hazardEn:
      "Ambiguous or unclear presentation of settings, measurements or other information",
    defaultNoteTr:
      "Hatalı veya eksik etiketleme yanlış kullanıma sebep olabilir.",
    defaultNoteEn: "Incorrect or incomplete labeling may cause improper use.",
  },
  {
    id: "E2.031",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Sonuçların yanlış yorumlanması",
    hazardEn: "Misinterpretation of results",
    defaultNoteTr: "Ürün yorumlama yapmamaktadır.",
    defaultNoteEn: "Product does not interpret.",
    naIfNoSoftware: true,
  },
  {
    id: "E2.032",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Görünürlüğün, işitilebilirliğin veya dokunulabilirliğin yetersizliği",
    hazardEn: "Insufficient visibility, audibility or tactility",
    defaultNoteTr:
      "Etiketin okunabilir olmaması hatalı kullanıma sebep olabilir.",
    defaultNoteEn: "Insufficient legible of label can cause improper use.",
  },
  {
    id: "E2.033",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr:
      "Kontrolle hareketin veya görüntülenen bilgi ile gerçek durumun iyi örtüşmemesi",
    hazardEn:
      "Poor mapping of controls to actions, or of displayed information to actual state",
    defaultNoteTr:
      "Ürün kontrol ile hareket ettirilmemekte, görüntü vermemektedir.",
    defaultNoteEn:
      "Products are not moved with the control, do not include display.",
    naIfNoSoftware: true,
  },
  {
    id: "E2.034",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr:
      "Mevcut cihazla karşılaştırıldığında tartışmalı modlar veya eşlenmeler",
    hazardEn: "Disputable mode or match when compared with existing device",
    defaultNoteTr:
      "Ürünü başka bir cihaz ile karşılaştırmak mümkün değildir.",
    defaultNoteEn: "It is not possible to compare product with another device.",
  },
  {
    id: "E2.035",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Cihazın beceriksiz/eğitimsiz kişiler tarafından kullanılması",
    hazardEn: "Use by unskilled/untrained personnel",
    defaultNoteTr:
      "Yetenekli/eğitimli olmayan kişilerce kullanılması hataya sebep olur.",
    defaultNoteEn: "Unprofessional handling causes error.",
  },
  {
    id: "E2.036",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Yan etkiler için yeterince uyarılar bulunmaması",
    hazardEn: "Insufficient warning for side effects",
    defaultNoteTr:
      "Uyarı ve yan etki tanımlanmaması başarısızlığa sebep olabilir.",
    defaultNoteEn:
      "Non description of side effects and warnings may cause failure.",
  },
  {
    id: "E2.037",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr:
      "Tek kullanımlık tıbbi cihazın tekrar kullanılmasıyla ilgili tehlike uyarısının yetersizliği",
    hazardEn:
      "Inadequate warning of hazards associated with re-use of single-use medical devices",
    defaultNoteTr: "Etiket üzerinde tek kullanımlık sembolü mevcuttur.",
    defaultNoteEn: "Single use symbol is available on label.",
    naIfNonReusable: true,
  },
  {
    id: "E2.038",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Yanlış ölçmeler ve diğer metrolojik hususlar",
    hazardEn: "Incorrect measurement and other metrological aspects",
    defaultNoteTr: "Ölçüm ve metrolojik fonksiyonlar mevcut değildir.",
    defaultNoteEn: "Measurement and metrological functions are unavailable.",
  },
  {
    id: "E2.039",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr:
      "Tüketim malzemeleri/aksesuarlar/diğer tıbbi cihazlarla uyumsuzluk",
    hazardEn: "Incompatibility with consumables/accessories/other medical devices",
    defaultNoteTr: "Uygulanamıyor.",
    defaultNoteEn: "Unavailable.",
  },
  {
    id: "E2.040",
    table: "E2",
    categoryTr: "İnsan Faktörü",
    categoryEn: "Human Factors",
    groupTr: "Tasarım kusurlarıyla tetiklenen kullanım hataları",
    groupEn: "Usage errors triggered by design failure",
    hazardTr: "Keskin kenarlar ve sivri uçlar",
    hazardEn: "Slips, laps and mistakes",
    defaultNoteTr: "Çapak mevcudiyeti enfeksiyon yaratır.",
    defaultNoteEn: "The presence of burrs creates infection.",
  },
  // — Hata Modları —
  {
    id: "E2.041",
    table: "E2",
    categoryTr: "Hata Modları",
    categoryEn: "Failure Modes",
    hazardTr: "Beklenmeyen elektriksel/mekanik bütünlük kaybı",
    hazardEn: "Unexpected loss of electrical/mechanical integrity",
    defaultNoteTr:
      "Doktor hatası beklenmeyen mekanik bütünlük kaybı oluşturabilir; elektriksel kayıp mevcut değildir.",
    defaultNoteEn:
      "Doctor error may create unexpected loss of mechanical integrity; electrical loss does not exist.",
  },
  {
    id: "E2.042",
    table: "E2",
    categoryTr: "Hata Modları",
    categoryEn: "Failure Modes",
    hazardTr:
      "Yaşlanma, aşınma ve tekrarlanan kullanımın sonucu olarak işlevselliğin bozulması",
    hazardEn:
      "Deterioration in function as a result of ageing, wear and repeated use",
    defaultNoteTr:
      "Ürünün uygun olmayan yerlerde ve şekilde kullanımı; yaşlanma ve aşınma oluşabilir.",
    defaultNoteEn:
      "Depending on nonconforming use of location and shape, deterioration in function may occur on the product.",
    naIfNonReusable: true,
  },
  {
    id: "E2.043",
    table: "E2",
    categoryTr: "Hata Modları",
    categoryEn: "Failure Modes",
    hazardTr: "Ürün yorgunluğu",
    hazardEn: "Fatigue failure",
    defaultNoteTr: "Kullanım şekline bağlı olarak ürün yorgunluğu oluşabilir.",
    defaultNoteEn: "Depending on shape of use, fatigue may occur on the products.",
  },
];

export const ALL_TABLE_E_SEEDS: TableESeed[] = [
  ...TABLE_E1_SEEDS,
  ...TABLE_E2_SEEDS,
];
