import { findTableESeed } from "@/lib/domain/risk-table-e";

const STOP_WORDS = new Set(["and", "or", "of", "the", "a", "an", "for", "in", "on", "to", "per"]);

/** English category name → initials (e.g. "Transport and Storage" → "TS"). */
export function categoryInitialsFromEnglish(category: string): string {
  const words = category
    .trim()
    .split(/\s+/)
    .map((w) => w.replace(/[^a-zA-Z]/g, ""))
    .filter((w) => w.length > 0 && !STOP_WORDS.has(w.toLowerCase()));

  if (words.length === 0) return "R";
  if (words.length === 1) {
    const w = words[0].toUpperCase();
    return w.length >= 2 ? w.slice(0, 2) : w;
  }
  return words.map((w) => w[0]!.toUpperCase()).join("");
}

export function formatCategoryRiskNo(categoryEn: string, indexInCategory: number): string {
  const prefix = categoryInitialsFromEnglish(categoryEn);
  return `${prefix}${Math.max(1, indexInCategory)}`;
}

export function resolveRiskCategoryEn(item: {
  tableERef?: string | null;
  riskSource?: string | null;
}): string {
  if (item.tableERef) {
    const seed = findTableESeed(item.tableERef);
    if (seed?.categoryEn?.trim()) return seed.categoryEn.trim();
  }
  return "General";
}

/** System-assigned codes (legacy RTE or category initials + index). */
export function isAutoGeneratedRiskNo(riskNo: string | null | undefined): boolean {
  const v = riskNo?.trim() ?? "";
  if (!v) return true;
  if (/^RTE\d+$/i.test(v)) return true;
  return /^[A-Z]{1,8}\d+$/i.test(v);
}

export interface RiskItemForCoding {
  id: string;
  riskNo?: string | null;
  tableERef?: string | null;
  riskSource?: string | null;
}

/** Assign risk numbers per Table E category: EH1, EH2, TS1, … */
export function computeRiskNumbersByCategory(items: RiskItemForCoding[]): Map<string, string> {
  const categoryCounters = new Map<string, number>();
  const result = new Map<string, string>();

  for (const item of items) {
    if (!isAutoGeneratedRiskNo(item.riskNo)) {
      result.set(item.id, item.riskNo!.trim());
      continue;
    }
    const categoryEn = resolveRiskCategoryEn(item);
    const next = (categoryCounters.get(categoryEn) ?? 0) + 1;
    categoryCounters.set(categoryEn, next);
    result.set(item.id, formatCategoryRiskNo(categoryEn, next));
  }

  return result;
}

export function displayRiskNo(
  item: RiskItemForCoding,
  allItems?: RiskItemForCoding[],
): string {
  const raw = item.riskNo?.trim();
  if (raw && !isAutoGeneratedRiskNo(raw)) return raw;
  if (raw && !/^RTE\d+$/i.test(raw)) return raw;
  if (allItems?.length) {
    const computed = computeRiskNumbersByCategory(allItems);
    return computed.get(item.id) ?? raw ?? "—";
  }
  if (raw) return raw;
  return formatCategoryRiskNo(resolveRiskCategoryEn(item), 1);
}
